# Further Reading Suggestions {#sec-appendix-reading}

This book is, of course, not comprehensive when it comes to highlighting the R programming language. Because of this, the list below are suggested readings that will increase your knowledge/skill of R.

## Introduction to R Programming Books

1.  [R for Data Science: Import, Tidy, Transform, Visualize, and Model Data](https://amzn.to/3ovLXUB)

2.  [Hands-On Programming with R: Write Your Own Functions and Simulations](https://amzn.to/3PYUVWf)

3.  [The Book of R: A First Course in Programming and Statistics](https://amzn.to/3J8lWEv)

4.  [Learning R: A Step-by-Step Function Guide to Data Analysis](https://amzn.to/3zcjYhA)

5.  [The Art of R Programming: A Tour of Statistical Software Design](https://amzn.to/3OBMjn2)

6.  [Advanced R (Second Edition)](https://amzn.to/3zbBT8f)

## Data Visualization in R and Visualization Guides

1.  [R Graphics Cookbook: Practical Recipes for Visualizing Data](https://amzn.to/3oulxTa)

2.  [Storytelling with Data: A Data Visualization Guides for Business Professionals](https://amzn.to/3PAOB7y)

3.  [Better Data Visualizations: A Guide for Scholars, Researchers, and Wonks](https://amzn.to/3PE3QfP)

## Sport Analytics Guides/Books

1.  [The Midrange Theory: Basketball's Evolution in the Age of Analytics](https://amzn.to/3PE2LEK)

2.  [Analyzing Baseball Data with R (2nd edition)](https://amzn.to/3vgIyNl)

3.  [A Fan's Guide to Baseball Analytics: Why WAR, WHIP, wOBA, and other Advanced Sabermetrics Are Essential to Understanding Modern Baseball](https://amzn.to/3zwXcCA)

4.  [The Book: Playing the Percentages in Baseball](https://amzn.to/3vgR3rM)

5.  [The Hidden Game of Baseball: A Revolutionary Approach to Baseball and Its Statistics](https://amzn.to/3oy66t4)

6.  [The Hidden Game of Football: A Revealing and Lively Look at the Pro Game, With New Stats, Revolutionary Strategies, and Keys to Picking the Winners](https://amzn.to/3PZt7kf)

7.  [Mathletics: How Gamblers, Managers, and Fans Use Mathematics in Sports](https://amzn.to/3zwXysU)

8.  [Basketball Data Science: With Applications in R](https://amzn.to/3Bnd23U)

9.  [Data Analytics in Football (Soccer): Positional Data Collection, Modelling, and Analysis](https://amzn.to/3PE4bPA)
