<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>An Introduction to NFL Analytics Using R - 2&nbsp; An Introduction to NFL Analytics and the R Programming Language</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./02-nfl-analytics-tidyverse.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-0ZLEFZL898"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-0ZLEFZL898', { 'anonymize_ip': true});
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">
<span class="chapter-number">2</span>&nbsp; <span class="chapter-title">An Introduction to NFL Analytics and the R Programming Language</span>
</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">An Introduction to NFL Analytics Using R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/bcongelio/nfl-analytics-with-r-book" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="" title="Share" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-share"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
<li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
            <i class="bi bi-bi-twitter pe-1"></i>
          Twitter
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
            <i class="bi bi-bi-facebook pe-1"></i>
          Facebook
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
            <i class="bi bi-bi-linkedin pe-1"></i>
          LinkedIn
          </a>
        </li>
    </ul>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-nfl-analytics-and-r.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">An Introduction to NFL Analytics and the R Programming Language</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-nfl-analytics-tidyverse.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Wrangling NFL Data in the <code>tidyverse</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-nfl-analytics-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Working With The <code>nflverse</code> Functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-nfl-analytics-visualization.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Visualization with NFL Analytics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a1-nfl-analytics-dictionary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">NFL Analytics Reference Guide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a2-nfl-further-reading.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Further Reading Suggestions</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#nflreadr-an-introduction-to-the-data" id="toc-nflreadr-an-introduction-to-the-data" class="nav-link active" data-scroll-target="#nflreadr-an-introduction-to-the-data"> <span class="header-section-number">2.1</span> <code>nflreadr</code>: An Introduction to the Data</a>
  <ul class="collapse">
<li><a href="#getting-weekly-player-stats-via-load_player_stats" id="toc-getting-weekly-player-stats-via-load_player_stats" class="nav-link" data-scroll-target="#getting-weekly-player-stats-via-load_player_stats"> <span class="header-section-number">2.1.1</span> Getting Weekly Player Stats via <code>load_player_stats()</code></a></li>
  <li><a href="#using-load_player_stats-to-find-leaders" id="toc-using-load_player_stats-to-find-leaders" class="nav-link" data-scroll-target="#using-load_player_stats-to-find-leaders"> <span class="header-section-number">2.1.2</span> Using <code>load_player_stats()</code> To Find Leaders</a></li>
  </ul>
</li>
  <li>
<a href="#using-load_pbp-to-add-context-to-statistics" id="toc-using-load_pbp-to-add-context-to-statistics" class="nav-link" data-scroll-target="#using-load_pbp-to-add-context-to-statistics"> <span class="header-section-number">2.2</span> Using <code>load_pbp()</code> to Add Context to Statistics</a>
  <ul class="collapse">
<li><a href="#an-example-qb-aggressiveness-on-3rd-down" id="toc-an-example-qb-aggressiveness-on-3rd-down" class="nav-link" data-scroll-target="#an-example-qb-aggressiveness-on-3rd-down"> <span class="header-section-number">2.2.1</span> An Example: QB Aggressiveness on 3rd Down</a></li>
  <li><a href="#the-inclusion-of-contextual-statistics" id="toc-the-inclusion-of-contextual-statistics" class="nav-link" data-scroll-target="#the-inclusion-of-contextual-statistics"> <span class="header-section-number">2.2.2</span> The Inclusion of Contextual Statistics</a></li>
  </ul>
</li>
  <li><a href="#retrieving-working-with-data-for-multiple-seasons" id="toc-retrieving-working-with-data-for-multiple-seasons" class="nav-link" data-scroll-target="#retrieving-working-with-data-for-multiple-seasons"> <span class="header-section-number">2.3</span> Retrieving &amp; Working With Data for Multiple Seasons</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"> <span class="header-section-number">2.4</span> Exercises</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title d-none d-lg-block">
<span class="chapter-number">2</span>&nbsp; <span class="chapter-title">An Introduction to NFL Analytics and the R Programming Language</span>
</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><p>As mentioned in the Preface of this book, the <code>nflverse</code> has drastically expanded since the inception of <code>nflfastR</code> in April of 2020. In total, the current version of the <code>nflverse</code> is comprised of five separate R packages:</p>
<ol type="1">
<li><code>nflfastR</code></li>
<li><code>nflseedR</code></li>
<li><code>nfl4th</code></li>
<li><code>nflreadr</code></li>
<li><code>nflplotR</code></li>
</ol>
<p>Installing the <code>nflverse</code> as a package in R will automatically install all five packages. However, the core focus of this book will be on <code>nflreadr</code>. It is understandable if you are confused by that, since the Preface of this book introduced the <code>nflfastR</code> package. The <code>nflreadr</code> package, as explained by its author (<a href="https://tanho.ca/">Tan Ho</a>), is a “minimal package for downloading data from <code>nflverse</code> repositories.” The data that <em>is</em> the <code>nflverse</code> is stored across five different GitHub repositories. Using <code>nflreadr</code> allows for easy access to any of these data sources. For lack of a better term, <code>nflreadr</code> acts as a shortcut of sorts while also operating with less dependencies.</p>
<p>As you will see in this chapter, using <code>nflreadr::</code> while coding provides nearly identical functions to those available when using <code>nflfastR::</code>. In fact, <code>nflfastR::</code>, in many instances, now calls, “under the hood,” the equivalent function in <code>nflreadr::</code>. Because of the coalescing between the two, many of the new functions being developed are available only when using <code>nflreadr::</code>. For example, <code>nflreadr::</code> allows you to access data pertaining to the NFL Combine, draft picks, contracts, trades, injury information, and access to statistics on Pro Football Reference.</p>
<p>While <code>nflfastR</code> did initially serve as the foundation of the “amateur NFL analytics” movement, the <code>nflreadr</code> package has superseded it and now serves as the “catchall” package for all the various bits and pieces of the <code>nflverse</code>. Because of this, and to maintain consistency throughout, this book - nearly exclusively - will use <code>nflreadr::</code> when calling functions housed within the <code>nflverse</code> rather than <code>nflfastR::</code>.</p>
<p>The below diagram visualizes the relationship between <code>nflfastR</code> and <code>nflreadr</code>.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/updated-diagram.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Comparing nflfastR to nflreadr</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The purpose of this chapter is to explore <code>nflreadr</code> data in an introductory fashion using, what I believe, are the two most important functions in the <code>nflverse</code>: (1.) <code>load_player_stats()</code> and (2.) <code>load_pbp()</code>. It makes the assumption that you are versed in the R programming language. If you are not, please start with Chapter 2 where you can learn about R and the <code>tidyverse</code> language using examples from the <code>nflverse</code>.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you are completely new to the R programming language (or you have not yet downloaded and installed both R and RStudio, please read Chapter 2 prior to continuing with this introductory chapter.</p>
</div>
</div>
<section id="nflreadr-an-introduction-to-the-data" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="nflreadr-an-introduction-to-the-data">
<span class="header-section-number">2.1</span> <code>nflreadr</code>: An Introduction to the Data</h2>
<p>The most important part of the <code>nflverse</code> is, of course, the data. To begin, we will examine the core data that underpins the <code>nflverse</code>: weekly player stats and the more detailed play-by–play data. Using <code>nflreadr</code>, the end user is able to collect weekly top-level stats via the <code>load_player_stats()</code> function or the much more robust play-by-play numbers by using the <code>load_pbp()</code> function.</p>
<p>As you may imagine, there is a <strong>very important distinction between the <code>load_player_stats()</code></strong> <strong>and <code>load_pbp()</code></strong>. As mentioned, <code>load_player_stats()</code> will provide you with weekly, pre-calculated statistics for either offense or kicking. Conversely, <code>load_pbp()</code> will provide over 350 metrics for every single play of every single game dating back to 1999.</p>
<p>The <code>load_player_stats()</code> function includes the following offensive information:</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">offensive.stats</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_player_stats.html">load_player_stats</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="va">offensive.stats</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "air_yards_share"             "attempts"                   
 [3] "carries"                     "completions"                
 [5] "dakota"                      "fantasy_points"             
 [7] "fantasy_points_ppr"          "headshot_url"               
 [9] "interceptions"               "pacr"                       
[11] "passing_2pt_conversions"     "passing_air_yards"          
[13] "passing_epa"                 "passing_first_downs"        
[15] "passing_tds"                 "passing_yards"              
[17] "passing_yards_after_catch"   "player_display_name"        
[19] "player_id"                   "player_name"                
[21] "position"                    "position_group"             
[23] "racr"                        "receiving_2pt_conversions"  
[25] "receiving_air_yards"         "receiving_epa"              
[27] "receiving_first_downs"       "receiving_fumbles"          
[29] "receiving_fumbles_lost"      "receiving_tds"              
[31] "receiving_yards"             "receiving_yards_after_catch"
[33] "recent_team"                 "receptions"                 
[35] "rushing_2pt_conversions"     "rushing_epa"                
[37] "rushing_first_downs"         "rushing_fumbles"            
[39] "rushing_fumbles_lost"        "rushing_tds"                
[41] "rushing_yards"               "sack_fumbles"               
[43] "sack_fumbles_lost"           "sack_yards"                 
[45] "sacks"                       "season"                     
[47] "season_type"                 "special_teams_tds"          
[49] "target_share"                "targets"                    
[51] "week"                        "wopr"                       </code></pre>
</div>
</div>
<p>As well, switching the <code>stat_type</code> to “kicking” provides the following information:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">kicking.stats</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_player_stats.html">load_player_stats</a></span><span class="op">(</span><span class="fl">2021</span>, stat_type <span class="op">=</span> <span class="st">"kicking"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="va">kicking.stats</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "fg_att"              "fg_blocked"          "fg_blocked_distance"
 [4] "fg_blocked_list"     "fg_long"             "fg_made"            
 [7] "fg_made_0_19"        "fg_made_20_29"       "fg_made_30_39"      
[10] "fg_made_40_49"       "fg_made_50_59"       "fg_made_60_"        
[13] "fg_made_distance"    "fg_made_list"        "fg_missed"          
[16] "fg_missed_0_19"      "fg_missed_20_29"     "fg_missed_30_39"    
[19] "fg_missed_40_49"     "fg_missed_50_59"     "fg_missed_60_"      
[22] "fg_missed_distance"  "fg_missed_list"      "fg_pct"             
[25] "gwfg_att"            "gwfg_blocked"        "gwfg_distance"      
[28] "gwfg_made"           "gwfg_missed"         "pat_att"            
[31] "pat_blocked"         "pat_made"            "pat_missed"         
[34] "pat_pct"             "player_id"           "player_name"        
[37] "season"              "season_type"         "team"               
[40] "week"               </code></pre>
</div>
</div>
<p>While the data returned is not as rich as the play-by-play data we will covering next, the <code>load_player_stats()</code> function is extremely helpful when you need to quickly (and correctly!) recreate the official stats listed on either the NFL’s website or on <a href="https://www.pro-football-reference.com/">Pro Football Reference</a>.</p>
<p>As an example, let’s say you need to get Ben Roethlisberger’s total passing yard and attempts from the 2021 season. You could do so via <code>load_pbp()</code> but, if you do not need further context, using <code>load_player_stats()</code> is much more efficient.</p>
<section id="getting-weekly-player-stats-via-load_player_stats" class="level3" data-number="2.1.1"><h3 data-number="2.1.1" class="anchored" data-anchor-id="getting-weekly-player-stats-via-load_player_stats">
<span class="header-section-number">2.1.1</span> Getting Weekly Player Stats via <code>load_player_stats()</code>
</h3>
<p>If you are familiar with R, it might seem logical to do the following to get Roethlisberger’s total passing yards and number of attempts from the 2021 regular season:</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">weekly.data</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_player_stats.html">load_player_stats</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span>

<span class="va">ben.weekly</span> <span class="op">&lt;-</span> <span class="va">weekly.data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_id</span>, <span class="va">player_name</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span> <span class="op">&amp;</span> <span class="va">player_name</span> <span class="op">==</span> <span class="st">"B.Roethlisberger"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>total.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_yards</span><span class="op">)</span>,
            n.attempts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">attempts</span><span class="op">)</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'player_id'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu">tibble</span><span class="op">(</span><span class="va">ben.weekly</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 x 4
  player_id  player_name      total.yards n.attempts
  &lt;chr&gt;      &lt;chr&gt;                  &lt;dbl&gt;      &lt;int&gt;
1 00-0022924 B.Roethlisberger        3740        605</code></pre>
</div>
</div>
<p>As you can see in the <code>ben.weekly</code> output, we have matched his official 2021 regular stats perfectly with 3,740 passing yards on 605 attempts. The code we just created is doing several things. First, we are using <code>nflreadr::load_player_stats(2021)</code> to place the data into our R environment in a DF titled <code>weekly.data</code>.</p>
<p>Next, we group the data together by alike <code>player_id</code> (as every individual player has a unique ID number) as well as the player’s actual name. At the filtering level, we are looking for just the regular season (<code>REG</code>) within <code>season_type</code> and also removing all quarterbacks except for Ben Roethlisberger. It is important to note that player names are just first initial and last name, without a space after the period.</p>
<p>After filtering for the regular season, we are able to summarize all of the weekly data into combined statistics by summing the weekly totals of passing yards and attempts.</p>
<p><strong>However, filtering by <code>player_name</code> can lead to significant issues with your results.</strong> An excellent example of this is Josh Allen. Let’s recreate the code above that successfully provided Roethlisberger’s stats, but replace Ben with Josh Allen:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">josh.allen</span> <span class="op">&lt;-</span> <span class="va">weekly.data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_name</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">player_name</span> <span class="op">==</span> <span class="st">"J.Allen"</span> <span class="op">&amp;</span> <span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>total.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_yards</span><span class="op">)</span>,
            n.attempts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">attempts</span><span class="op">)</span><span class="op">)</span>

<span class="fu">tibble</span><span class="op">(</span><span class="va">josh.allen</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 x 3
  player_name total.yards n.attempts
  &lt;chr&gt;             &lt;dbl&gt;      &lt;int&gt;
1 J.Allen            4407        646</code></pre>
</div>
</div>
<p>The output tells us Allen threw for 4,049 yards on 603 attempts during the 2021 regular season. A check of his <a href="https://www.pro-football-reference.com/players/A/AlleJo02.htm">Pro Football Reference page</a> tells us those numbers are incorrect. In fact, he had 4,407 passing yards on 646 attempts. How did we end up 358 passing yards and 43 attempts short?</p>
<p>The answer comes from Aaron Schatz, the creator of <a href="https://www.footballoutsiders.com/">Football Outsiders</a>, who explained in a <a href="https://twitter.com/fo_aschatz/status/1442191416826888192?s=21">Tweet</a> that the official Buffalo Bills’ scorer, during week 3 of the NFL season, decided to refer to Allen as “Jos.Allen” as a result of the Washington Commanders having a player named “Jonathan Allen.”</p>
<p>To double check this, we can run the same code as above, but remove the <code>player_name</code> filter and switch to searching for just those players on the Buffalo Bills by using <code>recent_team</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">two.josh.allens</span> <span class="op">&lt;-</span> <span class="va">weekly.data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_id</span>, <span class="va">player_name</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span> <span class="op">&amp;</span> <span class="va">recent_team</span> <span class="op">==</span> <span class="st">"BUF"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>total.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_yards</span><span class="op">)</span>,
            n.attempts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">attempts</span><span class="op">)</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'player_id'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu">tibble</span><span class="op">(</span><span class="va">two.josh.allens</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 x 4
   player_id  player_name  total.yards n.attempts
   &lt;chr&gt;      &lt;chr&gt;              &lt;dbl&gt;      &lt;int&gt;
 1 00-0027685 E.Sanders              0          0
 2 00-0029000 C.Beasley              0          1
 3 00-0031588 S.Diggs                0          0
 4 00-0031787 J.Kumerow              0          0
 5 00-0033308 M.Breida               0          0
 6 00-0033466 I.McKenzie             0          0
 7 00-0033550 D.Webb                 0          0
 8 00-0033869 M.Trubisky            43          8
 9 00-0033904 D.Dawkins              0          0
10 00-0034857 J.Allen             4407        646
11 00-0035250 D.Singletary           0          0
12 00-0035308 T.Sweeney              0          0
13 00-0035689 D.Knox                 0          0
14 00-0036187 R.Gilliam              0          0
15 00-0036196 G.Davis                0          0
16 00-0036251 Z.Moss                 0          0</code></pre>
</div>
</div>
<p>Grouping by <code>player_id</code> and <code>player_name</code> (as well as filtering down to Buffalo), we can see that, indeed, Josh Allen is in the data twice under the same <code>player_id</code>. Moreover, if you do the math, you can see that the numbers from his two entries add up to the official statistics on his Pro Football Reference page.</p>
<section id="using-load_player_stats-correctly" class="level4" data-number="2.1.1.1"><h4 data-number="2.1.1.1" class="anchored" data-anchor-id="using-load_player_stats-correctly">
<span class="header-section-number">2.1.1.1</span> Using <code>load_player_stats()</code> Correctly</h4>
<p>To avoid these situations, you <em>could</em> load up NFL rosters via the <code><a href="https://nflreadr.nflverse.com/reference/load_rosters.html">nflreadr::load_rosters()</a></code> function, but that would require unnecessary code in order to merge the two DFs together by matching the <code>player_id</code> to the <code>gsis_id</code> number found within the roster information. Doing so would correct the above issue of Josh Allen appearing in the data under different spellings. Instead, and to write the minimal amount of code to complete the task, we can do the following:</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">josh.allen</span> <span class="op">&lt;-</span> <span class="va">weekly.data</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_id</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>player_name <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">player_name</span><span class="op">)</span>,
            total.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_yards</span><span class="op">)</span>,
            n.attempts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">attempts</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">player_name</span> <span class="op">==</span> <span class="st">"J.Allen"</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The most efficient way to gather correct player statistics is to do the <code>group_by</code> with ONLY the <code>player_id</code> as, despite the variation in name, the <code>player_id</code> remained the same for Josh Allen. In order to include his correct name in the output, we can gather QB names within the <code>summarize</code> prior to calculating the sum of <code>passing_yards</code> and <code>attempts</code>. After, if you desire to see only Josh Allen’s number, you can filter out to just his name.</p>
</section></section><section id="using-load_player_stats-to-find-leaders" class="level3" data-number="2.1.2"><h3 data-number="2.1.2" class="anchored" data-anchor-id="using-load_player_stats-to-find-leaders">
<span class="header-section-number">2.1.2</span> Using <code>load_player_stats()</code> To Find Leaders</h3>
<p>While using <code>load_player_stats()</code> does not provide the ability to add context to your analysis as we will soon see with <code>load_pbp()</code>, it does provide an easy and efficient way to determine weekly or season-long leaders over many top-level, widely-used NFL statistics. In the below example, we will determine the 2021 leaders in air yards per attempt.</p>
<section id="an-example-2021-qb-air-yards-per-attempt-leaders" class="level4" data-number="2.1.2.1"><h4 data-number="2.1.2.1" class="anchored" data-anchor-id="an-example-2021-qb-air-yards-per-attempt-leaders">
<span class="header-section-number">2.1.2.1</span> An Example: 2021 QB Air Yards per Attempt Leaders</h4>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_player_stats.html">load_player_stats</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span>

<span class="va">ay.per.attempt</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_id</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>player_name <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">player_name</span><span class="op">)</span>,
            n.attempts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">attempts</span><span class="op">)</span>,
            n.airyards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_air_yards</span><span class="op">)</span>,
            ay.attempt <span class="op">=</span> <span class="va">n.airyards</span> <span class="op">/</span> <span class="va">n.attempts</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">n.attempts</span> <span class="op">&gt;=</span> <span class="fl">400</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">player_name</span>, <span class="va">ay.attempt</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">arrange</span><span class="op">(</span><span class="op">-</span><span class="va">ay.attempt</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the above example, we are using <code>group_by</code> to combine the desired statistics based on each unique <code>player_id</code> to, again, avoid any issues with player names within the data. After filtering to include just those statistics for the regular season, we first use the <code>summarize</code> function to grab the first <code>player_name</code> associated with the <code>player_id</code>. After, we find two items: (1.) the total number of passing attempts by each QB which is outputted into a new row titled <code>n.attempts</code> and the regular season total of each QB’s air yards, again outputted into a new row titled <code>n.airyards</code>.</p>
<p>It is important to note that the final row created with the <code>summarize</code> function is not a statistic included within <code>load_player_stats()</code>. In order to find a QB’s average air yards per attempt, we must use the first two items we’ve created and do some simple division (the created <code>n.airyards</code> divided by <code>n.attempts</code>).</p>
<p>Finally, to “clear the noise” of those QBs with minimal attempts through the season, we included a filter to include only those passers with at least 400 attempts. After, we arrange the new DF by sorting the QBs in descending order by average air yards per attempt.</p>
<p>The end results look like this:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu">tibble</span><span class="op">(</span><span class="va">ay.per.attempt</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 x 2
   player_name   ay.attempt
   &lt;chr&gt;              &lt;dbl&gt;
 1 R.Wilson            9.89
 2 J.Hurts             8.99
 3 B.Mayfield          8.73
 4 M.Stafford          8.48
 5 J.Allen             8.20
 6 K.Cousins           8.16
 7 J.Burrow            8.12
 8 D.Carr              8.12
 9 T.Brady             8.10
10 T.Bridgewater       8.04
# ... with 15 more rows</code></pre>
</div>
</div>
<p>Russell Wilson led the NFL in 2021 with 9.89 air yards per attempt.</p>
</section></section></section><section id="using-load_pbp-to-add-context-to-statistics" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="using-load_pbp-to-add-context-to-statistics">
<span class="header-section-number">2.2</span> Using <code>load_pbp()</code> to Add Context to Statistics</h2>
<p>As just mentioned above, using the <code>load_pbp()</code> function is preferable when you are looking to add context to a player’s statistics, as the <code>load_player_stats()</code> function is, for all intents and purposes, aggregated statistics that limit your ability to find deeper meaning.</p>
<p>The <code>load_pbp()</code> function provides over 350 various metrics, as listed below:</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">pbp.data</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_pbp.html">load_pbp</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="va">pbp.data</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "aborted_play"                        
  [2] "air_epa"                             
  [3] "air_wpa"                             
  [4] "air_yards"                           
  [5] "assist_tackle"                       
  [6] "assist_tackle_1_player_id"           
  [7] "assist_tackle_1_player_name"         
  [8] "assist_tackle_1_team"                
  [9] "assist_tackle_2_player_id"           
 [10] "assist_tackle_2_player_name"         
 [11] "assist_tackle_2_team"                
 [12] "assist_tackle_3_player_id"           
 [13] "assist_tackle_3_player_name"         
 [14] "assist_tackle_3_team"                
 [15] "assist_tackle_4_player_id"           
 [16] "assist_tackle_4_player_name"         
 [17] "assist_tackle_4_team"                
 [18] "away_coach"                          
 [19] "away_score"                          
 [20] "away_team"                           
 [21] "away_timeouts_remaining"             
 [22] "away_wp"                             
 [23] "away_wp_post"                        
 [24] "blocked_player_id"                   
 [25] "blocked_player_name"                 
 [26] "comp_air_epa"                        
 [27] "comp_air_wpa"                        
 [28] "comp_yac_epa"                        
 [29] "comp_yac_wpa"                        
 [30] "complete_pass"                       
 [31] "cp"                                  
 [32] "cpoe"                                
 [33] "def_wp"                              
 [34] "defensive_extra_point_attempt"       
 [35] "defensive_extra_point_conv"          
 [36] "defensive_two_point_attempt"         
 [37] "defensive_two_point_conv"            
 [38] "defteam"                             
 [39] "defteam_score"                       
 [40] "defteam_score_post"                  
 [41] "defteam_timeouts_remaining"          
 [42] "desc"                                
 [43] "div_game"                            
 [44] "down"                                
 [45] "drive"                               
 [46] "drive_end_transition"                
 [47] "drive_end_yard_line"                 
 [48] "drive_ended_with_score"              
 [49] "drive_first_downs"                   
 [50] "drive_game_clock_end"                
 [51] "drive_game_clock_start"              
 [52] "drive_inside20"                      
 [53] "drive_play_count"                    
 [54] "drive_play_id_ended"                 
 [55] "drive_play_id_started"               
 [56] "drive_quarter_end"                   
 [57] "drive_quarter_start"                 
 [58] "drive_real_start_time"               
 [59] "drive_start_transition"              
 [60] "drive_start_yard_line"               
 [61] "drive_time_of_possession"            
 [62] "drive_yards_penalized"               
 [63] "end_clock_time"                      
 [64] "end_yard_line"                       
 [65] "ep"                                  
 [66] "epa"                                 
 [67] "extra_point_attempt"                 
 [68] "extra_point_prob"                    
 [69] "extra_point_result"                  
 [70] "fantasy"                             
 [71] "fantasy_id"                          
 [72] "fantasy_player_id"                   
 [73] "fantasy_player_name"                 
 [74] "fg_prob"                             
 [75] "field_goal_attempt"                  
 [76] "field_goal_result"                   
 [77] "first_down"                          
 [78] "first_down_pass"                     
 [79] "first_down_penalty"                  
 [80] "first_down_rush"                     
 [81] "fixed_drive"                         
 [82] "fixed_drive_result"                  
 [83] "forced_fumble_player_1_player_id"    
 [84] "forced_fumble_player_1_player_name"  
 [85] "forced_fumble_player_1_team"         
 [86] "forced_fumble_player_2_player_id"    
 [87] "forced_fumble_player_2_player_name"  
 [88] "forced_fumble_player_2_team"         
 [89] "fourth_down_converted"               
 [90] "fourth_down_failed"                  
 [91] "fumble"                              
 [92] "fumble_forced"                       
 [93] "fumble_lost"                         
 [94] "fumble_not_forced"                   
 [95] "fumble_out_of_bounds"                
 [96] "fumble_recovery_1_player_id"         
 [97] "fumble_recovery_1_player_name"       
 [98] "fumble_recovery_1_team"              
 [99] "fumble_recovery_1_yards"             
[100] "fumble_recovery_2_player_id"         
[101] "fumble_recovery_2_player_name"       
[102] "fumble_recovery_2_team"              
[103] "fumble_recovery_2_yards"             
[104] "fumbled_1_player_id"                 
[105] "fumbled_1_player_name"               
[106] "fumbled_1_team"                      
[107] "fumbled_2_player_id"                 
[108] "fumbled_2_player_name"               
[109] "fumbled_2_team"                      
[110] "game_date"                           
[111] "game_half"                           
[112] "game_id"                             
[113] "game_seconds_remaining"              
[114] "game_stadium"                        
[115] "goal_to_go"                          
[116] "half_sack_1_player_id"               
[117] "half_sack_1_player_name"             
[118] "half_sack_2_player_id"               
[119] "half_sack_2_player_name"             
[120] "half_seconds_remaining"              
[121] "home_coach"                          
[122] "home_opening_kickoff"                
[123] "home_score"                          
[124] "home_team"                           
[125] "home_timeouts_remaining"             
[126] "home_wp"                             
[127] "home_wp_post"                        
[128] "id"                                  
[129] "incomplete_pass"                     
[130] "interception"                        
[131] "interception_player_id"              
[132] "interception_player_name"            
[133] "jersey_number"                       
[134] "kick_distance"                       
[135] "kicker_player_id"                    
[136] "kicker_player_name"                  
[137] "kickoff_attempt"                     
[138] "kickoff_downed"                      
[139] "kickoff_fair_catch"                  
[140] "kickoff_in_endzone"                  
[141] "kickoff_inside_twenty"               
[142] "kickoff_out_of_bounds"               
[143] "kickoff_returner_player_id"          
[144] "kickoff_returner_player_name"        
[145] "lateral_interception_player_id"      
[146] "lateral_interception_player_name"    
[147] "lateral_kickoff_returner_player_id"  
[148] "lateral_kickoff_returner_player_name"
[149] "lateral_punt_returner_player_id"     
[150] "lateral_punt_returner_player_name"   
[151] "lateral_receiver_player_id"          
[152] "lateral_receiver_player_name"        
[153] "lateral_receiving_yards"             
[154] "lateral_reception"                   
[155] "lateral_recovery"                    
[156] "lateral_return"                      
[157] "lateral_rush"                        
[158] "lateral_rusher_player_id"            
[159] "lateral_rusher_player_name"          
[160] "lateral_rushing_yards"               
[161] "lateral_sack_player_id"              
[162] "lateral_sack_player_name"            
[163] "location"                            
[164] "name"                                
[165] "nfl_api_id"                          
[166] "no_huddle"                           
[167] "no_score_prob"                       
[168] "old_game_id"                         
[169] "opp_fg_prob"                         
[170] "opp_safety_prob"                     
[171] "opp_td_prob"                         
[172] "order_sequence"                      
[173] "out_of_bounds"                       
[174] "own_kickoff_recovery"                
[175] "own_kickoff_recovery_player_id"      
[176] "own_kickoff_recovery_player_name"    
[177] "own_kickoff_recovery_td"             
[178] "pass"                                
[179] "pass_attempt"                        
[180] "pass_defense_1_player_id"            
[181] "pass_defense_1_player_name"          
[182] "pass_defense_2_player_id"            
[183] "pass_defense_2_player_name"          
[184] "pass_length"                         
[185] "pass_location"                       
[186] "pass_oe"                             
[187] "pass_touchdown"                      
[188] "passer"                              
[189] "passer_id"                           
[190] "passer_jersey_number"                
[191] "passer_player_id"                    
[192] "passer_player_name"                  
[193] "passing_yards"                       
[194] "penalty"                             
[195] "penalty_player_id"                   
[196] "penalty_player_name"                 
[197] "penalty_team"                        
[198] "penalty_type"                        
[199] "penalty_yards"                       
[200] "play"                                
[201] "play_clock"                          
[202] "play_deleted"                        
[203] "play_id"                             
[204] "play_type"                           
[205] "play_type_nfl"                       
[206] "posteam"                             
[207] "posteam_score"                       
[208] "posteam_score_post"                  
[209] "posteam_timeouts_remaining"          
[210] "posteam_type"                        
[211] "punt_attempt"                        
[212] "punt_blocked"                        
[213] "punt_downed"                         
[214] "punt_fair_catch"                     
[215] "punt_in_endzone"                     
[216] "punt_inside_twenty"                  
[217] "punt_out_of_bounds"                  
[218] "punt_returner_player_id"             
[219] "punt_returner_player_name"           
[220] "punter_player_id"                    
[221] "punter_player_name"                  
[222] "qb_dropback"                         
[223] "qb_epa"                              
[224] "qb_hit"                              
[225] "qb_hit_1_player_id"                  
[226] "qb_hit_1_player_name"                
[227] "qb_hit_2_player_id"                  
[228] "qb_hit_2_player_name"                
[229] "qb_kneel"                            
[230] "qb_scramble"                         
[231] "qb_spike"                            
[232] "qtr"                                 
[233] "quarter_end"                         
[234] "quarter_seconds_remaining"           
[235] "receiver"                            
[236] "receiver_id"                         
[237] "receiver_jersey_number"              
[238] "receiver_player_id"                  
[239] "receiver_player_name"                
[240] "receiving_yards"                     
[241] "replay_or_challenge"                 
[242] "replay_or_challenge_result"          
[243] "result"                              
[244] "return_team"                         
[245] "return_touchdown"                    
[246] "return_yards"                        
[247] "roof"                                
[248] "run_gap"                             
[249] "run_location"                        
[250] "rush"                                
[251] "rush_attempt"                        
[252] "rush_touchdown"                      
[253] "rusher"                              
[254] "rusher_id"                           
[255] "rusher_jersey_number"                
[256] "rusher_player_id"                    
[257] "rusher_player_name"                  
[258] "rushing_yards"                       
[259] "sack"                                
[260] "sack_player_id"                      
[261] "sack_player_name"                    
[262] "safety"                              
[263] "safety_player_id"                    
[264] "safety_player_name"                  
[265] "safety_prob"                         
[266] "score_differential"                  
[267] "score_differential_post"             
[268] "season"                              
[269] "season_type"                         
[270] "series"                              
[271] "series_result"                       
[272] "series_success"                      
[273] "shotgun"                             
[274] "side_of_field"                       
[275] "solo_tackle"                         
[276] "solo_tackle_1_player_id"             
[277] "solo_tackle_1_player_name"           
[278] "solo_tackle_1_team"                  
[279] "solo_tackle_2_player_id"             
[280] "solo_tackle_2_player_name"           
[281] "solo_tackle_2_team"                  
[282] "sp"                                  
[283] "special"                             
[284] "special_teams_play"                  
[285] "spread_line"                         
[286] "st_play_type"                        
[287] "stadium"                             
[288] "stadium_id"                          
[289] "start_time"                          
[290] "success"                             
[291] "surface"                             
[292] "tackle_for_loss_1_player_id"         
[293] "tackle_for_loss_1_player_name"       
[294] "tackle_for_loss_2_player_id"         
[295] "tackle_for_loss_2_player_name"       
[296] "tackle_with_assist"                  
[297] "tackle_with_assist_1_player_id"      
[298] "tackle_with_assist_1_player_name"    
[299] "tackle_with_assist_1_team"           
[300] "tackle_with_assist_2_player_id"      
[301] "tackle_with_assist_2_player_name"    
[302] "tackle_with_assist_2_team"           
[303] "tackled_for_loss"                    
[304] "td_player_id"                        
[305] "td_player_name"                      
[306] "td_prob"                             
[307] "td_team"                             
[308] "temp"                                
[309] "third_down_converted"                
[310] "third_down_failed"                   
[311] "time"                                
[312] "time_of_day"                         
[313] "timeout"                             
[314] "timeout_team"                        
[315] "total"                               
[316] "total_away_comp_air_epa"             
[317] "total_away_comp_air_wpa"             
[318] "total_away_comp_yac_epa"             
[319] "total_away_comp_yac_wpa"             
[320] "total_away_epa"                      
[321] "total_away_pass_epa"                 
[322] "total_away_pass_wpa"                 
[323] "total_away_raw_air_epa"              
[324] "total_away_raw_air_wpa"              
[325] "total_away_raw_yac_epa"              
[326] "total_away_raw_yac_wpa"              
[327] "total_away_rush_epa"                 
[328] "total_away_rush_wpa"                 
[329] "total_away_score"                    
[330] "total_home_comp_air_epa"             
[331] "total_home_comp_air_wpa"             
[332] "total_home_comp_yac_epa"             
[333] "total_home_comp_yac_wpa"             
[334] "total_home_epa"                      
[335] "total_home_pass_epa"                 
[336] "total_home_pass_wpa"                 
[337] "total_home_raw_air_epa"              
[338] "total_home_raw_air_wpa"              
[339] "total_home_raw_yac_epa"              
[340] "total_home_raw_yac_wpa"              
[341] "total_home_rush_epa"                 
[342] "total_home_rush_wpa"                 
[343] "total_home_score"                    
[344] "total_line"                          
[345] "touchback"                           
[346] "touchdown"                           
[347] "two_point_attempt"                   
[348] "two_point_conv_result"               
[349] "two_point_conversion_prob"           
[350] "vegas_home_wp"                       
[351] "vegas_home_wpa"                      
[352] "vegas_wp"                            
[353] "vegas_wpa"                           
[354] "weather"                             
[355] "week"                                
[356] "wind"                                
[357] "wp"                                  
[358] "wpa"                                 
[359] "xpass"                               
[360] "xyac_epa"                            
[361] "xyac_fd"                             
[362] "xyac_mean_yardage"                   
[363] "xyac_median_yardage"                 
[364] "xyac_success"                        
[365] "yac_epa"                             
[366] "yac_wpa"                             
[367] "yardline_100"                        
[368] "yards_after_catch"                   
[369] "yards_gained"                        
[370] "ydsnet"                              
[371] "ydstogo"                             
[372] "yrdln"                               </code></pre>
</div>
</div>
<p>A bit overwhelming, right?</p>
<p>Luckily, the <code>nflfastR</code> website includes a searchable directory of all the variables with a brief description of what each one means. You can visit that here: <a href="https://www.nflfastr.com/articles/field_descriptions.html">nflfastR Field Descriptions</a>.</p>
<p>As seen above, we can use the <code>load_player_stats()</code> function to determine a QB’s average yards per attempt over the course of a season. But, what if we wanted to add context to that? For example, how do we explore a QB’s air yards in game-specific situations?</p>
<p>To showcase using <code>load_pbp()</code> to add context to your analysis, let’s explore QB performance via air yards on 3rd down.</p>
<section id="an-example-qb-aggressiveness-on-3rd-down" class="level3" data-number="2.2.1"><h3 data-number="2.2.1" class="anchored" data-anchor-id="an-example-qb-aggressiveness-on-3rd-down">
<span class="header-section-number">2.2.1</span> An Example: QB Aggressiveness on 3rd Down</h3>
<p>Sticking with the air yards example from above, let’s examine a metric I created using <code>load_pbp()</code> that I coined <strong>QB 3rd Down Aggressiveness</strong>. The metric is designed to determine which QBs in the NFL are most aggressive in 3rd down situations by gauging how often they throw the ball to, or pass, the first down line. It is an interesting metric to explore as, just like many metrics in the NFL, not all air yards are created equal. For example, eight air yards on 1st and 10 are less valuable than the same eight air yards on 3rd and 5.</p>
<p>First, let’s highlight the code used to create the results for this metric and then break it down line-by-line.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_pbp.html">load_pbp</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span>

<span class="va">aggressiveness</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer_id</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">down</span> <span class="op">==</span> <span class="fl">3</span>, <span class="va">play_type</span> <span class="op">==</span> <span class="st">"pass"</span>, <span class="va">ydstogo</span> <span class="op">&gt;=</span> <span class="fl">5</span>, <span class="va">ydstogo</span> <span class="op">&lt;=</span> <span class="fl">10</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>player_name <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">passer</span><span class="op">)</span>,
            team <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">posteam</span><span class="op">)</span>,
            total <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,
            aggressive <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">air_yards</span> <span class="op">&gt;=</span> <span class="va">ydstogo</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            percentage <span class="op">=</span> <span class="va">aggressive</span> <span class="op">/</span> <span class="va">total</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">total</span> <span class="op">&gt;=</span> <span class="fl">50</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">arrange</span><span class="op">(</span><span class="op">-</span><span class="va">percentage</span><span class="op">)</span>

<span class="fu">tibble</span><span class="op">(</span><span class="va">aggressiveness</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 x 6
   passer_id  player_name  team  total aggressive percentage
   &lt;chr&gt;      &lt;chr&gt;        &lt;chr&gt; &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;
 1 00-0033077 D.Prescott   DAL      84         53      0.631
 2 00-0035228 K.Murray     ARI      60         37      0.617
 3 00-0036389 J.Hurts      PHI      65         40      0.615
 4 00-0033873 P.Mahomes    KC       93         56      0.602
 5 00-0034855 B.Mayfield   CLE      59         35      0.593
 6 00-0036971 T.Lawrence   JAX      78         46      0.590
 7 00-0036355 J.Herbert    LAC      87         51      0.586
 8 00-0035710 D.Jones      NYG      60         35      0.583
 9 00-0036212 T.Tagovailoa MIA      60         35      0.583
10 00-0026498 M.Stafford   LA       95         54      0.568
# ... with 20 more rows</code></pre>
</div>
</div>
<p>As you can see in the <code>tibble()</code> output of the results, Dak Prescott was the most aggressive quarterback in 3rd down passing situations in the 2021 season, passing to, our beyond, the line of gain just over 63% of the time.</p>
<p>After creating a new dataframe called <code>aggressiveness</code> from the 2021 play-by-play we originally collected using <code>data &lt;- nflreadr::load_pbp(2021)</code>, we use <code>group_by</code> to ensure that the data is being collected <em>per individual quarterback</em> via <code>passer_id.</code></p>
<p>After using the <code>group_by</code> function to lump data with each individual QB, we then use <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> function. Of course, we only want those <code>play_types</code> that are “pass” on 3rd downs. However, in the above code, we are filtering for <em>just</em>&nbsp;those 3rd down situations where the <code>yards to go</code> are between five and ten yards.</p>
<p>Doing so was a personal decision on my end when creating the metric, as there are certainly arguments to be made regarding how to “capture” scenarios in the data that require “aggressiveness.” My logic? If there were less than five yards to go on 3rd down, the opposing defense would not be able to “sell out” to the pass as it would not be out of the question for an offense to attempt to gain the first down on the ground. Conversely, anything <em>over</em> ten yards likely results in the defense selling out to the pass, thus leaving an imprint on the aggressiveness output of the quarterbacks.</p>
<p>For the sake of curiosity, we can edit the above code to include all passing attempts on 3rd down with under 10 yards to go for the first down:</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">aggressiveness.under.10</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer_id</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">down</span> <span class="op">==</span> <span class="fl">3</span>, <span class="va">play_type</span> <span class="op">==</span> <span class="st">"pass"</span>, <span class="va">ydstogo</span> <span class="op">&lt;=</span> <span class="fl">10</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>player_name <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">passer</span><span class="op">)</span>,
            team <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">posteam</span><span class="op">)</span>,
            total <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,
            aggressive <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">air_yards</span> <span class="op">&gt;=</span> <span class="va">ydstogo</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            percentage <span class="op">=</span> <span class="va">aggressive</span> <span class="op">/</span> <span class="va">total</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">total</span> <span class="op">&gt;=</span> <span class="fl">50</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">arrange</span><span class="op">(</span><span class="fu">desc</span><span class="op">(</span><span class="va">percentage</span><span class="op">)</span><span class="op">)</span>

<span class="fu">tibble</span><span class="op">(</span><span class="va">aggressiveness.under.10</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 33 x 6
   passer_id  player_name  team  total aggressive percentage
   &lt;chr&gt;      &lt;chr&gt;        &lt;chr&gt; &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;
 1 00-0035228 K.Murray     ARI      98         67      0.684
 2 00-0036389 J.Hurts      PHI     107         73      0.682
 3 00-0036971 T.Lawrence   JAX     131         88      0.672
 4 00-0033077 D.Prescott   DAL     136         89      0.654
 5 00-0034857 J.Allen      BUF     138         88      0.638
 6 00-0036355 J.Herbert    LAC     148         94      0.635
 7 00-0036212 T.Tagovailoa MIA      93         59      0.634
 8 00-0026498 M.Stafford   LA      172        109      0.634
 9 00-0023459 A.Rodgers    GB      128         80      0.625
10 00-0035710 D.Jones      NYG      85         53      0.624
# ... with 23 more rows</code></pre>
</div>
</div>
<p>The results are quite different from the first running of this metric, as Dak Prescott is now the 4th most aggressive QB, while Kyler Murray moves to the top by approaching a nearly 70% aggressiveness rate on 3rd down. This small change highlights an important element about analytics: much of the work is the result of the coder (ie., <u>you</u>) being able to justify your decision-making process when developing the filters for each metric you create.</p>
<p>In this case, I stand by my argument that including just those pass attempts on 3rd down with between 5 and 10 yards to go is a more accurate assessment of aggressiveness as, for example, 3rd down with 8 yards to go is an obvious passing situation in <u>most</u> cases.</p>
<p>That begs the question, though: in which cases is 3rd down with 8 yards to go <u>not</u> an obvious passing situation? An example of this falls under the guise of “garbage time.”</p>
<section id="qb-aggressiveness-filtering-for-garbage-time" class="level4" data-number="2.2.1.1"><h4 data-number="2.2.1.1" class="anchored" data-anchor-id="qb-aggressiveness-filtering-for-garbage-time">
<span class="header-section-number">2.2.1.1</span> QB Aggressiveness: Filtering for “Garbage Time?”</h4>
<p>In our initial running of the QB Aggressiveness metric, Josh Allen is the 15th most aggressive QB in the NFL on 3rd down with between 5 and 10 yards to go. But how much does the success of the Buffalo Bills play into that 15th place ranking?</p>
<p>The Bills, at the conclusion of the 2021 season, had the largest positive point differential in the league at 194 (the Bills scored 483 points, while allowing just 289). Perhaps Allen’s numbers are skewed because the Bills were so often playing with the lead late into the game?</p>
<p>To account for this, we can add information into the <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> function to attempt to remove what are referenced to in the analytics community as “garbage time stats.”</p>
<p>Let’s add the “garbage time” filter to the code we’ve already prepared:</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">aggressiveness.garbage</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer_id</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">down</span> <span class="op">==</span> <span class="fl">3</span>, <span class="va">play_type</span> <span class="op">==</span> <span class="st">"pass"</span>, <span class="va">ydstogo</span> <span class="op">&gt;=</span> <span class="fl">5</span>, <span class="va">ydstogo</span> <span class="op">&lt;=</span> <span class="fl">10</span>,
         <span class="va">wp</span> <span class="op">&gt;</span> <span class="fl">.05</span>, <span class="va">wp</span> <span class="op">&lt;</span> <span class="fl">.95</span>, <span class="va">half_seconds_remaining</span> <span class="op">&gt;</span> <span class="fl">120</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>player_name <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">passer</span><span class="op">)</span>,
            team <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">posteam</span><span class="op">)</span>,
            total <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,
            aggressive <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">air_yards</span> <span class="op">&gt;=</span> <span class="va">ydstogo</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            percentage <span class="op">=</span> <span class="va">aggressive</span> <span class="op">/</span> <span class="va">total</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">total</span> <span class="op">&gt;=</span> <span class="fl">50</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">arrange</span><span class="op">(</span><span class="fu">desc</span><span class="op">(</span><span class="va">percentage</span><span class="op">)</span><span class="op">)</span>

<span class="fu">tibble</span><span class="op">(</span><span class="va">aggressiveness.garbage</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 26 x 6
   passer_id  player_name team  total aggressive percentage
   &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt; &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;
 1 00-0033077 D.Prescott  DAL      61         40      0.656
 2 00-0036971 T.Lawrence  JAX      51         33      0.647
 3 00-0035228 K.Murray    ARI      51         31      0.608
 4 00-0026498 M.Stafford  LA       79         48      0.608
 5 00-0033873 P.Mahomes   KC       68         41      0.603
 6 00-0035710 D.Jones     NYG      50         30      0.6  
 7 00-0036355 J.Herbert   LAC      67         38      0.567
 8 00-0036972 M.Jones     NE       57         31      0.544
 9 00-0034857 J.Allen     BUF      59         32      0.542
10 00-0029263 R.Wilson    SEA      56         30      0.536
# ... with 16 more rows</code></pre>
</div>
</div>
<p>We are now using the same code, but have included three new items to the <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code>. First, we are stipulating that, aside from the down and distance inclusion, we only want those plays that occurred when the offense’s <code>win probability</code> was between 5% and 95%, as well as ensuring that the plays did not happen after the two-minute warning of either half.</p>
<p>The decision on range of the <code>win probability</code> numbers is, again, a personal preference. When <code>nflfastR</code> was first released, analyst often used a 20-80% range for <code>win probability</code>. However, Sebastian Carl - one of the creators of the <code>nflverse</code> explained in the package’s Discord:</p>
<blockquote class="blockquote">
<p>Sebastian Carl: “I am generally very conservative with filtering plays using wp. Especially the vegas wp model can reach &gt;85% probs early in the game because it incorporates market lines. I never understood the 20% &lt;= wp &lt;= 80%”garbage time” filter. This is removing a ton of plays. My general advice is a lower boundary of something around 5% (i.e., 5% &lt;= wp &lt;= 95%).</p>
</blockquote>
<p>Ben Baldwin followed up on Carl’s thoughts:</p>
<blockquote class="blockquote">
<p>Ben Baldwin: “agree with this. 20-80% should only be used as a filter for looking at how run-heavy a team is (because outside of this range is when teams change behavior a lot). and possibly how teams behave on 4th downs. but not for team or player performance.”</p>
</blockquote>
<p>Based on that advice, I typically stick to the 5-95% range when filtering for <code>win probability</code> using play-by-play data. And, in this case, it did have an impact.</p>
<p>As mentioned, prior to filtering for garbage time, Allen was the 15th most aggressive QB in the league at nearly 52%. However, once filtering for garbage time, Allen rose to 9th most aggressive QB, with a slight increase of percentage to 54%.</p>
<p>What is interesting about the above example, though, is Dak Prescott and the Cowboys. Dallas maintained the second largest point differential in the league (530 points for and 358 points against, for a 172 point difference). Without the garbage time filter, Prescott was tops in the NFL with an aggressiveness rating of 63%.</p>
<p>Once adjusted for garbage time? Prescott remained atop the NFL with an aggressiveness rating of 65.5%.</p>
<p>Allen’s increase in the standings, and Prescott remaining best in the league, in this specific metric, is a possible indicator that the inclusion of the “garbage time” filters provides a slightly more accurate result.</p>
</section></section><section id="the-inclusion-of-contextual-statistics" class="level3" data-number="2.2.2"><h3 data-number="2.2.2" class="anchored" data-anchor-id="the-inclusion-of-contextual-statistics">
<span class="header-section-number">2.2.2</span> The Inclusion of Contextual Statistics</h3>
<p>As seen in the above example regarding QB aggressiveness on 3rd down, the using of the <code>load_pbp()</code> function provides the ability to create situation specific metrics that would otherwise be lost in aggregated weekly statistics.</p>
</section></section><section id="retrieving-working-with-data-for-multiple-seasons" class="level2" data-number="2.3"><h2 data-number="2.3" class="anchored" data-anchor-id="retrieving-working-with-data-for-multiple-seasons">
<span class="header-section-number">2.3</span> Retrieving &amp; Working With Data for Multiple Seasons</h2>
<p>In the case of both <code>load_pbp()</code> and <code>load_player_stats()</code>, it is possible to load data over multiple seasons.</p>
<p>In our above example calculating average air yard per attempt, it is important to note that Russell Wilson’s league-leading average of 9.89 air yards per attempt is calculated using <em>all</em> passing attempts, meaning pass attempts that were both complete and incomplete.</p>
<p>In our first example of working with data across multiple seasons, let’s examine average air yards for only completed passes. To begin, we will retrieve the play-by-play data for the last five seasons:</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">ay.five.years</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_pbp.html">load_pbp</a></span><span class="op">(</span><span class="fl">2017</span><span class="op">:</span><span class="fl">2021</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To retrieve multiple seasons of data, a colon <code>:</code> is placed between the years that you want. When you run the code, <code>nflreadr</code> will output the data to include the play-by-play data starting with the oldest season (in this case, the 2017 NFL season):</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="fu">tibble</span><span class="op">(</span><span class="va">ay.five.years</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 243,131 x 372
   play_id game_id old_g~1 home_~2 away_~3 seaso~4  week posteam poste~5 defteam
     &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  
 1       1 2017_0~ 201709~ DET     ARI     REG         1 &lt;NA&gt;    &lt;NA&gt;    &lt;NA&gt;   
 2      37 2017_0~ 201709~ DET     ARI     REG         1 ARI     away    DET    
 3      73 2017_0~ 201709~ DET     ARI     REG         1 ARI     away    DET    
 4      97 2017_0~ 201709~ DET     ARI     REG         1 ARI     away    DET    
 5     118 2017_0~ 201709~ DET     ARI     REG         1 ARI     away    DET    
 6     153 2017_0~ 201709~ DET     ARI     REG         1 ARI     away    DET    
 7     174 2017_0~ 201709~ DET     ARI     REG         1 ARI     away    DET    
 8     207 2017_0~ 201709~ DET     ARI     REG         1 ARI     away    DET    
 9     233 2017_0~ 201709~ DET     ARI     REG         1 DET     home    ARI    
10     254 2017_0~ 201709~ DET     ARI     REG         1 DET     home    ARI    
# ... with 243,121 more rows, 362 more variables: side_of_field &lt;chr&gt;,
#   yardline_100 &lt;dbl&gt;, game_date &lt;chr&gt;, quarter_seconds_remaining &lt;dbl&gt;,
#   half_seconds_remaining &lt;dbl&gt;, game_seconds_remaining &lt;dbl&gt;,
#   game_half &lt;chr&gt;, quarter_end &lt;dbl&gt;, drive &lt;dbl&gt;, sp &lt;dbl&gt;, qtr &lt;dbl&gt;,
#   down &lt;dbl&gt;, goal_to_go &lt;dbl&gt;, time &lt;chr&gt;, yrdln &lt;chr&gt;, ydstogo &lt;dbl&gt;,
#   ydsnet &lt;dbl&gt;, desc &lt;chr&gt;, play_type &lt;chr&gt;, yards_gained &lt;dbl&gt;,
#   shotgun &lt;dbl&gt;, no_huddle &lt;dbl&gt;, qb_dropback &lt;dbl&gt;, qb_kneel &lt;dbl&gt;, ...</code></pre>
</div>
</div>
<p>Once you have the data collected, we can run code that looks quite similar to our code above that explored 2021’s air yards per attempt leaders using <code>load_player_stats()</code>. In this case, however, we are including an additional filter to gather those passing attempts that results <em>only</em> in complete passes:</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span class="va">average.airyards</span> <span class="op">&lt;-</span> <span class="va">ay.five.years</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer_id</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span> <span class="op">&amp;</span> <span class="va">complete_pass</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>player <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">passer_player_name</span><span class="op">)</span>,
            completions <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">complete_pass</span><span class="op">)</span>,
            air.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">air_yards</span><span class="op">)</span>,
            average <span class="op">=</span> <span class="va">air.yards</span> <span class="op">/</span> <span class="va">completions</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">completions</span> <span class="op">&gt;=</span> <span class="fl">1000</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">arrange</span><span class="op">(</span><span class="op">-</span><span class="va">average</span><span class="op">)</span>

<span class="fu">tibble</span><span class="op">(</span><span class="va">average.airyards</span><span class="op">)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 22 x 5
   passer_id  player      completions air.yards average
   &lt;chr&gt;      &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
 1 00-0031503 J.Winston          1008      8174    8.11
 2 00-0033537 D.Watson           1186      8461    7.13
 3 00-0029263 R.Wilson           1603     10939    6.82
 4 00-0026143 M.Ryan             1954     13051    6.68
 5 00-0034855 B.Mayfield         1185      7858    6.63
 6 00-0034857 J.Allen            1245      8221    6.60
 7 00-0033077 D.Prescott         1613     10449    6.48
 8 00-0026498 M.Stafford         1668     10804    6.48
 9 00-0029701 R.Tannehill        1049      6680    6.37
10 00-0032950 C.Wentz            1505      9491    6.31
# ... with 12 more rows</code></pre>
</div>
</div>
<p>Of those QBs with at least 1,000 complete passes since the 2017 season, Jameis Winston has the highest average air yards per complete pass at 8.11.</p>
</section><section id="exercises" class="level2" data-number="2.4"><h2 data-number="2.4" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">2.4</span> Exercises</h2>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./02-nfl-analytics-tidyverse.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Wrangling NFL Data in the <code>tidyverse</code></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">NFL Analytics with R was written by Bradley J. Congelio.</div>   
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a></div>
  </div>
</footer>


</body></html>