<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>An Introduction to NFL Analytics with R - 4&nbsp; NFL Analytics with the nflverse Family of Packages</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04-nfl-analytics-visualization.html" rel="next">
<link href="./02-nfl-analytics-tidyverse.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-0ZLEFZL898"></script><script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-0ZLEFZL898', { 'anonymize_ip': true});
</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">
<span class="chapter-number">4</span>&nbsp; <span class="chapter-title">NFL Analytics with the <code>nflverse</code> Family of Packages</span>
</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">An Introduction to NFL Analytics with R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/bcongelio/nfl-analytics-with-r-book" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="" title="Share" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-share"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
<li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
            <i class="bi bi-bi-twitter pe-1"></i>
          Twitter
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
            <i class="bi bi-bi-facebook pe-1"></i>
          Facebook
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
            <i class="bi bi-bi-linkedin pe-1"></i>
          LinkedIn
          </a>
        </li>
    </ul>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-nfl-analytics-and-r.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">An Introduction to NFL Analytics and the R Programming Language</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-nfl-analytics-tidyverse.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Wrangling NFL Data in the <code>tidyverse</code></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-nfl-analytics-functions.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">NFL Analytics with the <code>nflverse</code> Family of Packages</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-nfl-analytics-visualization.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Visualization with NFL Analytics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a1-nfl-analytics-dictionary.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">NFL Analytics Reference Guide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./a2-nfl-further-reading.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Further Reading Suggestions</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#nflreadr-an-introduction-to-the-data" id="toc-nflreadr-an-introduction-to-the-data" class="nav-link active" data-scroll-target="#nflreadr-an-introduction-to-the-data"><span class="toc-section-number">4.1</span>  <code>nflreadr</code>: An Introduction to the Data</a>
  <ul class="collapse">
<li><a href="#getting-weekly-player-stats-via-load_player_stats" id="toc-getting-weekly-player-stats-via-load_player_stats" class="nav-link" data-scroll-target="#getting-weekly-player-stats-via-load_player_stats"><span class="toc-section-number">4.1.1</span>  Getting Weekly Player Stats via <code>load_player_stats()</code></a></li>
  <li><a href="#using-load_player_stats-to-find-leaders" id="toc-using-load_player_stats-to-find-leaders" class="nav-link" data-scroll-target="#using-load_player_stats-to-find-leaders"><span class="toc-section-number">4.1.2</span>  Using <code>load_player_stats()</code> To Find Leaders</a></li>
  </ul>
</li>
  <li>
<a href="#using-load_pbp-to-add-context-to-statistics" id="toc-using-load_pbp-to-add-context-to-statistics" class="nav-link" data-scroll-target="#using-load_pbp-to-add-context-to-statistics"><span class="toc-section-number">4.2</span>  Using <code>load_pbp()</code> to Add Context to Statistics</a>
  <ul class="collapse">
<li><a href="#an-example-qb-aggressiveness-on-3rd-down" id="toc-an-example-qb-aggressiveness-on-3rd-down" class="nav-link" data-scroll-target="#an-example-qb-aggressiveness-on-3rd-down"><span class="toc-section-number">4.2.1</span>  An Example: QB Aggressiveness on 3rd Down</a></li>
  <li><a href="#the-inclusion-of-contextual-statistics" id="toc-the-inclusion-of-contextual-statistics" class="nav-link" data-scroll-target="#the-inclusion-of-contextual-statistics"><span class="toc-section-number">4.2.2</span>  The Inclusion of Contextual Statistics</a></li>
  </ul>
</li>
  <li><a href="#retrieving-working-with-data-for-multiple-seasons" id="toc-retrieving-working-with-data-for-multiple-seasons" class="nav-link" data-scroll-target="#retrieving-working-with-data-for-multiple-seasons"><span class="toc-section-number">4.3</span>  Retrieving &amp; Working With Data for Multiple Seasons</a></li>
  <li>
<a href="#working-with-the-various-nflreadr-functions" id="toc-working-with-the-various-nflreadr-functions" class="nav-link" data-scroll-target="#working-with-the-various-nflreadr-functions"><span class="toc-section-number">4.4</span>  Working with the Various <code>nflreadr</code> Functions</a>
  <ul class="collapse">
<li><a href="#the-load_participation-function" id="toc-the-load_participation-function" class="nav-link" data-scroll-target="#the-load_participation-function"><span class="toc-section-number">4.4.1</span>  The <code>load_participation()</code> Function</a></li>
  <li><a href="#the-load_rosters-and-load_rosters_weekly-functions" id="toc-the-load_rosters-and-load_rosters_weekly-functions" class="nav-link" data-scroll-target="#the-load_rosters-and-load_rosters_weekly-functions"><span class="toc-section-number">4.4.2</span>  The <code>load_rosters()</code> and <code>load_rosters_weekly()</code> Functions</a></li>
  <li><a href="#the-load_teams-function" id="toc-the-load_teams-function" class="nav-link" data-scroll-target="#the-load_teams-function"><span class="toc-section-number">4.4.3</span>  The <code>load_teams()</code> Function</a></li>
  <li><a href="#the-load_schedules-function" id="toc-the-load_schedules-function" class="nav-link" data-scroll-target="#the-load_schedules-function"><span class="toc-section-number">4.4.4</span>  The <code>load_schedules()</code> Function</a></li>
  <li><a href="#the-load_officials-function" id="toc-the-load_officials-function" class="nav-link" data-scroll-target="#the-load_officials-function"><span class="toc-section-number">4.4.5</span>  The <code>load_officials()</code> Function</a></li>
  <li><a href="#the-load_trades-function" id="toc-the-load_trades-function" class="nav-link" data-scroll-target="#the-load_trades-function"><span class="toc-section-number">4.4.6</span>  The <code>load_trades()</code> Function</a></li>
  <li><a href="#the-load_draft_picks-function" id="toc-the-load_draft_picks-function" class="nav-link" data-scroll-target="#the-load_draft_picks-function"><span class="toc-section-number">4.4.7</span>  The <code>load_draft_picks()</code> Function</a></li>
  <li><a href="#the-load_combine-function" id="toc-the-load_combine-function" class="nav-link" data-scroll-target="#the-load_combine-function"><span class="toc-section-number">4.4.8</span>  The <code>load_combine()</code> Function</a></li>
  <li><a href="#the-load_nextgen_stats-function" id="toc-the-load_nextgen_stats-function" class="nav-link" data-scroll-target="#the-load_nextgen_stats-function"><span class="toc-section-number">4.4.9</span>  The <code>load_nextgen_stats()</code> Function</a></li>
  <li><a href="#the-load_depth_charts-function" id="toc-the-load_depth_charts-function" class="nav-link" data-scroll-target="#the-load_depth_charts-function"><span class="toc-section-number">4.4.10</span>  The <code>load_depth_charts()</code> Function</a></li>
  <li><a href="#the-load_injuries-function" id="toc-the-load_injuries-function" class="nav-link" data-scroll-target="#the-load_injuries-function"><span class="toc-section-number">4.4.11</span>  The <code>load_injuries()</code> Function</a></li>
  <li><a href="#the-load_espn_qbr-function" id="toc-the-load_espn_qbr-function" class="nav-link" data-scroll-target="#the-load_espn_qbr-function"><span class="toc-section-number">4.4.12</span>  The <code>load_espn_qbr()</code> Function</a></li>
  <li><a href="#the-load_pfr_advstats-function" id="toc-the-load_pfr_advstats-function" class="nav-link" data-scroll-target="#the-load_pfr_advstats-function"><span class="toc-section-number">4.4.13</span>  The <code>load_pfr_advstats()</code> Function</a></li>
  <li><a href="#the-load_snap_counts-function" id="toc-the-load_snap_counts-function" class="nav-link" data-scroll-target="#the-load_snap_counts-function"><span class="toc-section-number">4.4.14</span>  The <code>load_snap_counts()</code> Function</a></li>
  <li><a href="#the-load_contracts-function" id="toc-the-load_contracts-function" class="nav-link" data-scroll-target="#the-load_contracts-function"><span class="toc-section-number">4.4.15</span>  The <code>load_contracts()</code> Function</a></li>
  <li><a href="#the-clean_player_names-function" id="toc-the-clean_player_names-function" class="nav-link" data-scroll-target="#the-clean_player_names-function"><span class="toc-section-number">4.4.16</span>  The <code>clean_player_names()</code> Function</a></li>
  <li><a href="#the-clean_team_abbrs-function" id="toc-the-clean_team_abbrs-function" class="nav-link" data-scroll-target="#the-clean_team_abbrs-function"><span class="toc-section-number">4.4.17</span>  The <code>clean_team_abbrs()</code> Function</a></li>
  <li><a href="#the-clean_homeaway-function" id="toc-the-clean_homeaway-function" class="nav-link" data-scroll-target="#the-clean_homeaway-function"><span class="toc-section-number">4.4.18</span>  The <code>clean_homeaway()</code> Function</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title d-none d-lg-block">
<span class="chapter-number">4</span>&nbsp; <span class="chapter-title">NFL Analytics with the <code>nflverse</code> Family of Packages</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><p>As mentioned in the Preface of this book, the <code>nflverse</code> has drastically expanded since the inception of <code>nflfastR</code> in April of 2020. In total, the current version of the <code>nflverse</code> is comprised of five separate R packages:</p>
<ol type="1">
<li><code>nflfastR</code></li>
<li><code>nflseedR</code></li>
<li><code>nfl4th</code></li>
<li><code>nflreadr</code></li>
<li><code>nflplotR</code></li>
</ol>
<p>Installing the <code>nflverse</code> as a package in R will automatically install all five packages. However, the core focus of this book will be on <code>nflreadr</code>. It is understandable if you are confused by that, since the Preface of this book introduced the <code>nflfastR</code> package. The <code>nflreadr</code> package, as explained by its author (<a href="https://tanho.ca/">Tan Ho</a>), is a “minimal package for downloading data from <code>nflverse</code> repositories.” The data that <em>is</em> the <code>nflverse</code> is stored across five different GitHub repositories. Using <code>nflreadr</code> allows for easy access to any of these data sources. For lack of a better term, <code>nflreadr</code> acts as a shortcut of sorts while also operating with less dependencies.</p>
<p>As you will see in this chapter, using <code>nflreadr::</code> while coding provides nearly identical functions to those available when using <code>nflfastR::</code>. In fact, <code>nflfastR::</code>, in many instances, now calls, “under the hood,” the equivalent function in <code>nflreadr::</code>. Because of the coalescing between the two, many of the new functions being developed are available only when using <code>nflreadr::</code>. For example, <code>nflreadr::</code> allows you to access data pertaining to the NFL Combine, draft picks, contracts, trades, injury information, and access to statistics on Pro Football Reference.</p>
<p>While <code>nflfastR</code> did initially serve as the foundation of the “amateur NFL analytics” movement, the <code>nflreadr</code> package has superseded it and now serves as the “catchall” package for all the various bits and pieces of the <code>nflverse</code>. Because of this, and to maintain consistency throughout, this book - nearly exclusively - will use <code>nflreadr::</code> when calling functions housed within the <code>nflverse</code> rather than <code>nflfastR::</code>.</p>
<p>The below diagram visualizes the relationship between <code>nflfastR</code> and <code>nflreadr</code>.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="images/updated-diagram.png" class="img-fluid" style="width:100.0%"></p>
</div>
</div>
<p>The purpose of this chapter is to explore <code>nflreadr</code> data in an introductory fashion using, what I believe, are the two most important functions in the <code>nflverse</code>: (1.) <code>load_player_stats()</code> and (2.) <code>load_pbp()</code>. It makes the assumption that you are versed in the R programming language. If you are not, please start with Chapter 2 where you can learn about R and the <code>tidyverse</code> language using examples from the <code>nflverse</code>.</p>
<section id="nflreadr-an-introduction-to-the-data" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="nflreadr-an-introduction-to-the-data">
<span class="header-section-number">4.1</span> <code>nflreadr</code>: An Introduction to the Data</h2>
<p>The most important part of the <code>nflverse</code> is, of course, the data. To begin, we will examine the core data that underpins the <code>nflverse</code>: weekly player stats and the more detailed play-by–play data. Using <code>nflreadr</code>, the end user is able to collect weekly top-level stats via the <code>load_player_stats()</code> function or the much more robust play-by-play numbers by using the <code>load_pbp()</code> function.</p>
<p>As you may imagine, there is a <strong>very important distinction between the <code>load_player_stats()</code></strong> <strong>and <code>load_pbp()</code></strong>. As mentioned, <code>load_player_stats()</code> will provide you with weekly, pre-calculated statistics for either offense or kicking. Conversely, <code>load_pbp()</code> will provide over 350 metrics for every single play of every single game dating back to 1999.</p>
<p>The <code>load_player_stats()</code> function includes the following offensive information:</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">offensive.stats</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_player_stats.html">load_player_stats</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="va">offensive.stats</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "air_yards_share"             "attempts"                   
 [3] "carries"                     "completions"                
 [5] "dakota"                      "fantasy_points"             
 [7] "fantasy_points_ppr"          "headshot_url"               
 [9] "interceptions"               "pacr"                       
[11] "passing_2pt_conversions"     "passing_air_yards"          
[13] "passing_epa"                 "passing_first_downs"        
[15] "passing_tds"                 "passing_yards"              
[17] "passing_yards_after_catch"   "player_display_name"        
[19] "player_id"                   "player_name"                
[21] "position"                    "position_group"             
[23] "racr"                        "receiving_2pt_conversions"  
[25] "receiving_air_yards"         "receiving_epa"              
[27] "receiving_first_downs"       "receiving_fumbles"          
[29] "receiving_fumbles_lost"      "receiving_tds"              
[31] "receiving_yards"             "receiving_yards_after_catch"
[33] "recent_team"                 "receptions"                 
[35] "rushing_2pt_conversions"     "rushing_epa"                
[37] "rushing_first_downs"         "rushing_fumbles"            
[39] "rushing_fumbles_lost"        "rushing_tds"                
[41] "rushing_yards"               "sack_fumbles"               
[43] "sack_fumbles_lost"           "sack_yards"                 
[45] "sacks"                       "season"                     
[47] "season_type"                 "special_teams_tds"          
[49] "target_share"                "targets"                    
[51] "week"                        "wopr"                       </code></pre>
</div>
</div>
<p>As well, switching the <code>stat_type</code> to “kicking” provides the following information:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">kicking.stats</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_player_stats.html">load_player_stats</a></span><span class="op">(</span><span class="fl">2021</span>, stat_type <span class="op">=</span> <span class="st">"kicking"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="va">kicking.stats</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "fg_att"              "fg_blocked"          "fg_blocked_distance"
 [4] "fg_blocked_list"     "fg_long"             "fg_made"            
 [7] "fg_made_0_19"        "fg_made_20_29"       "fg_made_30_39"      
[10] "fg_made_40_49"       "fg_made_50_59"       "fg_made_60_"        
[13] "fg_made_distance"    "fg_made_list"        "fg_missed"          
[16] "fg_missed_0_19"      "fg_missed_20_29"     "fg_missed_30_39"    
[19] "fg_missed_40_49"     "fg_missed_50_59"     "fg_missed_60_"      
[22] "fg_missed_distance"  "fg_missed_list"      "fg_pct"             
[25] "gwfg_att"            "gwfg_blocked"        "gwfg_distance"      
[28] "gwfg_made"           "gwfg_missed"         "pat_att"            
[31] "pat_blocked"         "pat_made"            "pat_missed"         
[34] "pat_pct"             "player_id"           "player_name"        
[37] "season"              "season_type"         "team"               
[40] "week"               </code></pre>
</div>
</div>
<p>While the data returned is not as rich as the play-by-play data we will covering next, the <code>load_player_stats()</code> function is extremely helpful when you need to quickly (and correctly!) recreate the official stats listed on either the NFL’s website or on <a href="https://www.pro-football-reference.com/">Pro Football Reference</a>.</p>
<p>As an example, let’s say you need to get Ben Roethlisberger’s total passing yard and attempts from the 2021 season. You could do so via <code>load_pbp()</code> but, if you do not need further context, using <code>load_player_stats()</code> is much more efficient.</p>
<section id="getting-weekly-player-stats-via-load_player_stats" class="level3" data-number="4.1.1"><h3 data-number="4.1.1" class="anchored" data-anchor-id="getting-weekly-player-stats-via-load_player_stats">
<span class="header-section-number">4.1.1</span> Getting Weekly Player Stats via <code>load_player_stats()</code>
</h3>
<p>If you are familiar with R, it might seem logical to do the following to get Roethlisberger’s total passing yards and number of attempts from the 2021 regular season:</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">weekly.data</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_player_stats.html">load_player_stats</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ben.weekly</span> <span class="op">&lt;-</span> <span class="va">weekly.data</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_id</span>, <span class="va">player_name</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span> <span class="op">&amp;</span> <span class="va">player_name</span> <span class="op">==</span> <span class="st">"B.Roethlisberger"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>total.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_yards</span><span class="op">)</span>,</span>
<span>            n.attempts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">attempts</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">tibble</span><span class="op">(</span><span class="va">ben.weekly</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 x 4
  player_id  player_name      total.yards n.attempts
  &lt;chr&gt;      &lt;chr&gt;                  &lt;dbl&gt;      &lt;int&gt;
1 00-0022924 B.Roethlisberger        3740        605</code></pre>
</div>
</div>
<p>As you can see in the <code>ben.weekly</code> output, we have matched his official 2021 regular stats perfectly with 3,740 passing yards on 605 attempts. The code we just created is doing several things. First, we are using <code>nflreadr::load_player_stats(2021)</code> to place the data into our R environment in a DF titled <code>weekly.data</code>.</p>
<p>Next, we group the data together by alike <code>player_id</code> (as every individual player has a unique ID number) as well as the player’s actual name. At the filtering level, we are looking for just the regular season (<code>REG</code>) within <code>season_type</code> and also removing all quarterbacks except for Ben Roethlisberger. It is important to note that player names are just first initial and last name, without a space after the period.</p>
<p>After filtering for the regular season, we are able to summarize all of the weekly data into combined statistics by summing the weekly totals of passing yards and attempts.</p>
<p><strong>However, filtering by <code>player_name</code> can lead to significant issues with your results.</strong> An excellent example of this is Josh Allen. Let’s recreate the code above that successfully provided Roethlisberger’s stats, but replace Ben with Josh Allen:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">josh.allen</span> <span class="op">&lt;-</span> <span class="va">weekly.data</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_name</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">player_name</span> <span class="op">==</span> <span class="st">"J.Allen"</span> <span class="op">&amp;</span> <span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>total.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_yards</span><span class="op">)</span>,</span>
<span>            n.attempts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">attempts</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">tibble</span><span class="op">(</span><span class="va">josh.allen</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 x 3
  player_name total.yards n.attempts
  &lt;chr&gt;             &lt;dbl&gt;      &lt;int&gt;
1 J.Allen            4407        646</code></pre>
</div>
</div>
<p>The output tells us Allen threw for 4,049 yards on 603 attempts during the 2021 regular season. A check of his <a href="https://www.pro-football-reference.com/players/A/AlleJo02.htm">Pro Football Reference page</a> tells us those numbers are incorrect. In fact, he had 4,407 passing yards on 646 attempts. How did we end up 358 passing yards and 43 attempts short?</p>
<p>The answer comes from Aaron Schatz, the creator of <a href="https://www.footballoutsiders.com/">Football Outsiders</a>, who explained in a <a href="https://twitter.com/fo_aschatz/status/1442191416826888192?s=21">Tweet</a> that the official Buffalo Bills’ scorer, during week 3 of the NFL season, decided to refer to Allen as “Jos.Allen” as a result of the Washington Commanders having a player named “Jonathan Allen.”</p>
<p>To double check this, we can run the same code as above, but remove the <code>player_name</code> filter and switch to searching for just those players on the Buffalo Bills by using <code>recent_team</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">two.josh.allens</span> <span class="op">&lt;-</span> <span class="va">weekly.data</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_id</span>, <span class="va">player_name</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span> <span class="op">&amp;</span> <span class="va">recent_team</span> <span class="op">==</span> <span class="st">"BUF"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>total.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_yards</span><span class="op">)</span>,</span>
<span>            n.attempts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">attempts</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">tibble</span><span class="op">(</span><span class="va">two.josh.allens</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 x 4
   player_id  player_name  total.yards n.attempts
   &lt;chr&gt;      &lt;chr&gt;              &lt;dbl&gt;      &lt;int&gt;
 1 00-0027685 E.Sanders              0          0
 2 00-0029000 C.Beasley              0          1
 3 00-0031588 S.Diggs                0          0
 4 00-0031787 J.Kumerow              0          0
 5 00-0033308 M.Breida               0          0
 6 00-0033466 I.McKenzie             0          0
 7 00-0033550 D.Webb                 0          0
 8 00-0033869 M.Trubisky            43          8
 9 00-0033904 D.Dawkins              0          0
10 00-0034857 J.Allen             4407        646
11 00-0035250 D.Singletary           0          0
12 00-0035308 T.Sweeney              0          0
13 00-0035689 D.Knox                 0          0
14 00-0036187 R.Gilliam              0          0
15 00-0036196 G.Davis                0          0
16 00-0036251 Z.Moss                 0          0</code></pre>
</div>
</div>
<p>Grouping by <code>player_id</code> and <code>player_name</code> (as well as filtering down to Buffalo), we can see that, indeed, Josh Allen is in the data twice under the same <code>player_id</code>. Moreover, if you do the math, you can see that the numbers from his two entries add up to the official statistics on his Pro Football Reference page.</p>
<section id="using-load_player_stats-correctly" class="level4" data-number="4.1.1.1"><h4 data-number="4.1.1.1" class="anchored" data-anchor-id="using-load_player_stats-correctly">
<span class="header-section-number">4.1.1.1</span> Using <code>load_player_stats()</code> Correctly</h4>
<p>To avoid these situations, you <em>could</em> load up NFL rosters via the <code><a href="https://nflreadr.nflverse.com/reference/load_rosters.html">nflreadr::load_rosters()</a></code> function, but that would require unnecessary code in order to merge the two DFs together by matching the <code>player_id</code> to the <code>gsis_id</code> number found within the roster information. Doing so would correct the above issue of Josh Allen appearing in the data under different spellings. Instead, and to write the minimal amount of code to complete the task, we can do the following:</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">josh.allen</span> <span class="op">&lt;-</span> <span class="va">weekly.data</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_id</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>player_name <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">player_name</span><span class="op">)</span>,</span>
<span>            total.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_yards</span><span class="op">)</span>,</span>
<span>            n.attempts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">attempts</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">player_name</span> <span class="op">==</span> <span class="st">"J.Allen"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The most efficient way to gather correct player statistics is to do the <code>group_by</code> with ONLY the <code>player_id</code> as, despite the variation in name, the <code>player_id</code> remained the same for Josh Allen. In order to include his correct name in the output, we can gather QB names within the <code>summarize</code> prior to calculating the sum of <code>passing_yards</code> and <code>attempts</code>. After, if you desire to see only Josh Allen’s number, you can filter out to just his name.</p>
</section></section><section id="using-load_player_stats-to-find-leaders" class="level3" data-number="4.1.2"><h3 data-number="4.1.2" class="anchored" data-anchor-id="using-load_player_stats-to-find-leaders">
<span class="header-section-number">4.1.2</span> Using <code>load_player_stats()</code> To Find Leaders</h3>
<p>While using <code>load_player_stats()</code> does not provide the ability to add context to your analysis as we will soon see with <code>load_pbp()</code>, it does provide an easy and efficient way to determine weekly or season-long leaders over many top-level, widely-used NFL statistics. In the below example, we will determine the 2021 leaders in air yards per attempt.</p>
<section id="an-example-2021-qb-air-yards-per-attempt-leaders" class="level4" data-number="4.1.2.1"><h4 data-number="4.1.2.1" class="anchored" data-anchor-id="an-example-2021-qb-air-yards-per-attempt-leaders">
<span class="header-section-number">4.1.2.1</span> An Example: 2021 QB Air Yards per Attempt Leaders</h4>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_player_stats.html">load_player_stats</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ay.per.attempt</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_id</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>player_name <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">player_name</span><span class="op">)</span>,</span>
<span>            n.attempts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">attempts</span><span class="op">)</span>,</span>
<span>            n.airyards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_air_yards</span><span class="op">)</span>,</span>
<span>            ay.attempt <span class="op">=</span> <span class="va">n.airyards</span> <span class="op">/</span> <span class="va">n.attempts</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">n.attempts</span> <span class="op">&gt;=</span> <span class="fl">400</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">player_name</span>, <span class="va">ay.attempt</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">arrange</span><span class="op">(</span><span class="op">-</span><span class="va">ay.attempt</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the above example, we are using <code>group_by</code> to combine the desired statistics based on each unique <code>player_id</code> to, again, avoid any issues with player names within the data. After filtering to include just those statistics for the regular season, we first use the <code>summarize</code> function to grab the first <code>player_name</code> associated with the <code>player_id</code>. After, we find two items: (1.) the total number of passing attempts by each QB which is outputted into a new row titled <code>n.attempts</code> and the regular season total of each QB’s air yards, again outputted into a new row titled <code>n.airyards</code>.</p>
<p>It is important to note that the final row created with the <code>summarize</code> function is not a statistic included within <code>load_player_stats()</code>. In order to find a QB’s average air yards per attempt, we must use the first two items we’ve created and do some simple division (the created <code>n.airyards</code> divided by <code>n.attempts</code>).</p>
<p>Finally, to “clear the noise” of those QBs with minimal attempts through the season, we included a filter to include only those passers with at least 400 attempts. After, we arrange the new DF by sorting the QBs in descending order by average air yards per attempt.</p>
<p>The end results look like this:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 25 x 2
   player_name   ay.attempt
   &lt;chr&gt;              &lt;dbl&gt;
 1 R.Wilson            9.89
 2 J.Hurts             8.99
 3 B.Mayfield          8.73
 4 M.Stafford          8.48
 5 J.Allen             8.20
 6 K.Cousins           8.16
 7 J.Burrow            8.12
 8 D.Carr              8.12
 9 T.Brady             8.10
10 T.Bridgewater       8.04
# ... with 15 more rows</code></pre>
</div>
</div>
<p>Russell Wilson led the NFL in 2021 with 9.89 air yards per attempt.</p>
</section></section></section><section id="using-load_pbp-to-add-context-to-statistics" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="using-load_pbp-to-add-context-to-statistics">
<span class="header-section-number">4.2</span> Using <code>load_pbp()</code> to Add Context to Statistics</h2>
<p>As just mentioned above, using the <code>load_pbp()</code> function is preferable when you are looking to add context to a player’s statistics, as the <code>load_player_stats()</code> function is, for all intents and purposes, aggregated statistics that limit your ability to find deeper meaning.</p>
<p>The <code>load_pbp()</code> function provides over 350 various metrics, as listed below:</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">pbp.data</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_pbp.html">load_pbp</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="va">pbp.data</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "aborted_play"                        
  [2] "air_epa"                             
  [3] "air_wpa"                             
  [4] "air_yards"                           
  [5] "assist_tackle"                       
  [6] "assist_tackle_1_player_id"           
  [7] "assist_tackle_1_player_name"         
  [8] "assist_tackle_1_team"                
  [9] "assist_tackle_2_player_id"           
 [10] "assist_tackle_2_player_name"         
 [11] "assist_tackle_2_team"                
 [12] "assist_tackle_3_player_id"           
 [13] "assist_tackle_3_player_name"         
 [14] "assist_tackle_3_team"                
 [15] "assist_tackle_4_player_id"           
 [16] "assist_tackle_4_player_name"         
 [17] "assist_tackle_4_team"                
 [18] "away_coach"                          
 [19] "away_score"                          
 [20] "away_team"                           
 [21] "away_timeouts_remaining"             
 [22] "away_wp"                             
 [23] "away_wp_post"                        
 [24] "blocked_player_id"                   
 [25] "blocked_player_name"                 
 [26] "comp_air_epa"                        
 [27] "comp_air_wpa"                        
 [28] "comp_yac_epa"                        
 [29] "comp_yac_wpa"                        
 [30] "complete_pass"                       
 [31] "cp"                                  
 [32] "cpoe"                                
 [33] "def_wp"                              
 [34] "defensive_extra_point_attempt"       
 [35] "defensive_extra_point_conv"          
 [36] "defensive_two_point_attempt"         
 [37] "defensive_two_point_conv"            
 [38] "defteam"                             
 [39] "defteam_score"                       
 [40] "defteam_score_post"                  
 [41] "defteam_timeouts_remaining"          
 [42] "desc"                                
 [43] "div_game"                            
 [44] "down"                                
 [45] "drive"                               
 [46] "drive_end_transition"                
 [47] "drive_end_yard_line"                 
 [48] "drive_ended_with_score"              
 [49] "drive_first_downs"                   
 [50] "drive_game_clock_end"                
 [51] "drive_game_clock_start"              
 [52] "drive_inside20"                      
 [53] "drive_play_count"                    
 [54] "drive_play_id_ended"                 
 [55] "drive_play_id_started"               
 [56] "drive_quarter_end"                   
 [57] "drive_quarter_start"                 
 [58] "drive_real_start_time"               
 [59] "drive_start_transition"              
 [60] "drive_start_yard_line"               
 [61] "drive_time_of_possession"            
 [62] "drive_yards_penalized"               
 [63] "end_clock_time"                      
 [64] "end_yard_line"                       
 [65] "ep"                                  
 [66] "epa"                                 
 [67] "extra_point_attempt"                 
 [68] "extra_point_prob"                    
 [69] "extra_point_result"                  
 [70] "fantasy"                             
 [71] "fantasy_id"                          
 [72] "fantasy_player_id"                   
 [73] "fantasy_player_name"                 
 [74] "fg_prob"                             
 [75] "field_goal_attempt"                  
 [76] "field_goal_result"                   
 [77] "first_down"                          
 [78] "first_down_pass"                     
 [79] "first_down_penalty"                  
 [80] "first_down_rush"                     
 [81] "fixed_drive"                         
 [82] "fixed_drive_result"                  
 [83] "forced_fumble_player_1_player_id"    
 [84] "forced_fumble_player_1_player_name"  
 [85] "forced_fumble_player_1_team"         
 [86] "forced_fumble_player_2_player_id"    
 [87] "forced_fumble_player_2_player_name"  
 [88] "forced_fumble_player_2_team"         
 [89] "fourth_down_converted"               
 [90] "fourth_down_failed"                  
 [91] "fumble"                              
 [92] "fumble_forced"                       
 [93] "fumble_lost"                         
 [94] "fumble_not_forced"                   
 [95] "fumble_out_of_bounds"                
 [96] "fumble_recovery_1_player_id"         
 [97] "fumble_recovery_1_player_name"       
 [98] "fumble_recovery_1_team"              
 [99] "fumble_recovery_1_yards"             
[100] "fumble_recovery_2_player_id"         
[101] "fumble_recovery_2_player_name"       
[102] "fumble_recovery_2_team"              
[103] "fumble_recovery_2_yards"             
[104] "fumbled_1_player_id"                 
[105] "fumbled_1_player_name"               
[106] "fumbled_1_team"                      
[107] "fumbled_2_player_id"                 
[108] "fumbled_2_player_name"               
[109] "fumbled_2_team"                      
[110] "game_date"                           
[111] "game_half"                           
[112] "game_id"                             
[113] "game_seconds_remaining"              
[114] "game_stadium"                        
[115] "goal_to_go"                          
[116] "half_sack_1_player_id"               
[117] "half_sack_1_player_name"             
[118] "half_sack_2_player_id"               
[119] "half_sack_2_player_name"             
[120] "half_seconds_remaining"              
[121] "home_coach"                          
[122] "home_opening_kickoff"                
[123] "home_score"                          
[124] "home_team"                           
[125] "home_timeouts_remaining"             
[126] "home_wp"                             
[127] "home_wp_post"                        
[128] "id"                                  
[129] "incomplete_pass"                     
[130] "interception"                        
[131] "interception_player_id"              
[132] "interception_player_name"            
[133] "jersey_number"                       
[134] "kick_distance"                       
[135] "kicker_player_id"                    
[136] "kicker_player_name"                  
[137] "kickoff_attempt"                     
[138] "kickoff_downed"                      
[139] "kickoff_fair_catch"                  
[140] "kickoff_in_endzone"                  
[141] "kickoff_inside_twenty"               
[142] "kickoff_out_of_bounds"               
[143] "kickoff_returner_player_id"          
[144] "kickoff_returner_player_name"        
[145] "lateral_interception_player_id"      
[146] "lateral_interception_player_name"    
[147] "lateral_kickoff_returner_player_id"  
[148] "lateral_kickoff_returner_player_name"
[149] "lateral_punt_returner_player_id"     
[150] "lateral_punt_returner_player_name"   
[151] "lateral_receiver_player_id"          
[152] "lateral_receiver_player_name"        
[153] "lateral_receiving_yards"             
[154] "lateral_reception"                   
[155] "lateral_recovery"                    
[156] "lateral_return"                      
[157] "lateral_rush"                        
[158] "lateral_rusher_player_id"            
[159] "lateral_rusher_player_name"          
[160] "lateral_rushing_yards"               
[161] "lateral_sack_player_id"              
[162] "lateral_sack_player_name"            
[163] "location"                            
[164] "name"                                
[165] "nfl_api_id"                          
[166] "no_huddle"                           
[167] "no_score_prob"                       
[168] "old_game_id"                         
[169] "opp_fg_prob"                         
[170] "opp_safety_prob"                     
[171] "opp_td_prob"                         
[172] "order_sequence"                      
[173] "out_of_bounds"                       
[174] "own_kickoff_recovery"                
[175] "own_kickoff_recovery_player_id"      
[176] "own_kickoff_recovery_player_name"    
[177] "own_kickoff_recovery_td"             
[178] "pass"                                
[179] "pass_attempt"                        
[180] "pass_defense_1_player_id"            
[181] "pass_defense_1_player_name"          
[182] "pass_defense_2_player_id"            
[183] "pass_defense_2_player_name"          
[184] "pass_length"                         
[185] "pass_location"                       
[186] "pass_oe"                             
[187] "pass_touchdown"                      
[188] "passer"                              
[189] "passer_id"                           
[190] "passer_jersey_number"                
[191] "passer_player_id"                    
[192] "passer_player_name"                  
[193] "passing_yards"                       
[194] "penalty"                             
[195] "penalty_player_id"                   
[196] "penalty_player_name"                 
[197] "penalty_team"                        
[198] "penalty_type"                        
[199] "penalty_yards"                       
[200] "play"                                
[201] "play_clock"                          
[202] "play_deleted"                        
[203] "play_id"                             
[204] "play_type"                           
[205] "play_type_nfl"                       
[206] "posteam"                             
[207] "posteam_score"                       
[208] "posteam_score_post"                  
[209] "posteam_timeouts_remaining"          
[210] "posteam_type"                        
[211] "punt_attempt"                        
[212] "punt_blocked"                        
[213] "punt_downed"                         
[214] "punt_fair_catch"                     
[215] "punt_in_endzone"                     
[216] "punt_inside_twenty"                  
[217] "punt_out_of_bounds"                  
[218] "punt_returner_player_id"             
[219] "punt_returner_player_name"           
[220] "punter_player_id"                    
[221] "punter_player_name"                  
[222] "qb_dropback"                         
[223] "qb_epa"                              
[224] "qb_hit"                              
[225] "qb_hit_1_player_id"                  
[226] "qb_hit_1_player_name"                
[227] "qb_hit_2_player_id"                  
[228] "qb_hit_2_player_name"                
[229] "qb_kneel"                            
[230] "qb_scramble"                         
[231] "qb_spike"                            
[232] "qtr"                                 
[233] "quarter_end"                         
[234] "quarter_seconds_remaining"           
[235] "receiver"                            
[236] "receiver_id"                         
[237] "receiver_jersey_number"              
[238] "receiver_player_id"                  
[239] "receiver_player_name"                
[240] "receiving_yards"                     
[241] "replay_or_challenge"                 
[242] "replay_or_challenge_result"          
[243] "result"                              
[244] "return_team"                         
[245] "return_touchdown"                    
[246] "return_yards"                        
[247] "roof"                                
[248] "run_gap"                             
[249] "run_location"                        
[250] "rush"                                
[251] "rush_attempt"                        
[252] "rush_touchdown"                      
[253] "rusher"                              
[254] "rusher_id"                           
[255] "rusher_jersey_number"                
[256] "rusher_player_id"                    
[257] "rusher_player_name"                  
[258] "rushing_yards"                       
[259] "sack"                                
[260] "sack_player_id"                      
[261] "sack_player_name"                    
[262] "safety"                              
[263] "safety_player_id"                    
[264] "safety_player_name"                  
[265] "safety_prob"                         
[266] "score_differential"                  
[267] "score_differential_post"             
[268] "season"                              
[269] "season_type"                         
[270] "series"                              
[271] "series_result"                       
[272] "series_success"                      
[273] "shotgun"                             
[274] "side_of_field"                       
[275] "solo_tackle"                         
[276] "solo_tackle_1_player_id"             
[277] "solo_tackle_1_player_name"           
[278] "solo_tackle_1_team"                  
[279] "solo_tackle_2_player_id"             
[280] "solo_tackle_2_player_name"           
[281] "solo_tackle_2_team"                  
[282] "sp"                                  
[283] "special"                             
[284] "special_teams_play"                  
[285] "spread_line"                         
[286] "st_play_type"                        
[287] "stadium"                             
[288] "stadium_id"                          
[289] "start_time"                          
[290] "success"                             
[291] "surface"                             
[292] "tackle_for_loss_1_player_id"         
[293] "tackle_for_loss_1_player_name"       
[294] "tackle_for_loss_2_player_id"         
[295] "tackle_for_loss_2_player_name"       
[296] "tackle_with_assist"                  
[297] "tackle_with_assist_1_player_id"      
[298] "tackle_with_assist_1_player_name"    
[299] "tackle_with_assist_1_team"           
[300] "tackle_with_assist_2_player_id"      
[301] "tackle_with_assist_2_player_name"    
[302] "tackle_with_assist_2_team"           
[303] "tackled_for_loss"                    
[304] "td_player_id"                        
[305] "td_player_name"                      
[306] "td_prob"                             
[307] "td_team"                             
[308] "temp"                                
[309] "third_down_converted"                
[310] "third_down_failed"                   
[311] "time"                                
[312] "time_of_day"                         
[313] "timeout"                             
[314] "timeout_team"                        
[315] "total"                               
[316] "total_away_comp_air_epa"             
[317] "total_away_comp_air_wpa"             
[318] "total_away_comp_yac_epa"             
[319] "total_away_comp_yac_wpa"             
[320] "total_away_epa"                      
[321] "total_away_pass_epa"                 
[322] "total_away_pass_wpa"                 
[323] "total_away_raw_air_epa"              
[324] "total_away_raw_air_wpa"              
[325] "total_away_raw_yac_epa"              
[326] "total_away_raw_yac_wpa"              
[327] "total_away_rush_epa"                 
[328] "total_away_rush_wpa"                 
[329] "total_away_score"                    
[330] "total_home_comp_air_epa"             
[331] "total_home_comp_air_wpa"             
[332] "total_home_comp_yac_epa"             
[333] "total_home_comp_yac_wpa"             
[334] "total_home_epa"                      
[335] "total_home_pass_epa"                 
[336] "total_home_pass_wpa"                 
[337] "total_home_raw_air_epa"              
[338] "total_home_raw_air_wpa"              
[339] "total_home_raw_yac_epa"              
[340] "total_home_raw_yac_wpa"              
[341] "total_home_rush_epa"                 
[342] "total_home_rush_wpa"                 
[343] "total_home_score"                    
[344] "total_line"                          
[345] "touchback"                           
[346] "touchdown"                           
[347] "two_point_attempt"                   
[348] "two_point_conv_result"               
[349] "two_point_conversion_prob"           
[350] "vegas_home_wp"                       
[351] "vegas_home_wpa"                      
[352] "vegas_wp"                            
[353] "vegas_wpa"                           
[354] "weather"                             
[355] "week"                                
[356] "wind"                                
[357] "wp"                                  
[358] "wpa"                                 
[359] "xpass"                               
[360] "xyac_epa"                            
[361] "xyac_fd"                             
[362] "xyac_mean_yardage"                   
[363] "xyac_median_yardage"                 
[364] "xyac_success"                        
[365] "yac_epa"                             
[366] "yac_wpa"                             
[367] "yardline_100"                        
[368] "yards_after_catch"                   
[369] "yards_gained"                        
[370] "ydsnet"                              
[371] "ydstogo"                             
[372] "yrdln"                               </code></pre>
</div>
</div>
<p>A bit overwhelming, right?</p>
<p>Luckily, the <code>nflfastR</code> website includes a searchable directory of all the variables with a brief description of what each one means. You can visit that here: <a href="https://www.nflfastr.com/articles/field_descriptions.html">nflfastR Field Descriptions</a>.</p>
<p>As seen above, we can use the <code>load_player_stats()</code> function to determine a QB’s average yards per attempt over the course of a season. But, what if we wanted to add context to that? For example, how do we explore a QB’s air yards in game-specific situations?</p>
<p>To showcase using <code>load_pbp()</code> to add context to your analysis, let’s explore QB performance via air yards on 3rd down.</p>
<section id="an-example-qb-aggressiveness-on-3rd-down" class="level3" data-number="4.2.1"><h3 data-number="4.2.1" class="anchored" data-anchor-id="an-example-qb-aggressiveness-on-3rd-down">
<span class="header-section-number">4.2.1</span> An Example: QB Aggressiveness on 3rd Down</h3>
<p>Sticking with the air yards example from above, let’s examine a metric I created using <code>load_pbp()</code> that I coined <strong>QB 3rd Down Aggressiveness</strong>. The metric is designed to determine which QBs in the NFL are most aggressive in 3rd down situations by gauging how often they throw the ball to, or pass, the first down line. It is an interesting metric to explore as, just like many metrics in the NFL, not all air yards are created equal. For example, eight air yards on 1st and 10 are less valuable than the same eight air yards on 3rd and 5.</p>
<p>First, let’s highlight the code used to create the results for this metric and then break it down line-by-line.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_pbp.html">load_pbp</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span></span>
<span></span>
<span><span class="va">aggressiveness</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer_id</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">down</span> <span class="op">==</span> <span class="fl">3</span>, <span class="va">play_type</span> <span class="op">==</span> <span class="st">"pass"</span>, <span class="va">ydstogo</span> <span class="op">&gt;=</span> <span class="fl">5</span>, <span class="va">ydstogo</span> <span class="op">&lt;=</span> <span class="fl">10</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>player_name <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">passer</span><span class="op">)</span>,</span>
<span>            team <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">posteam</span><span class="op">)</span>,</span>
<span>            total <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,</span>
<span>            aggressive <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">air_yards</span> <span class="op">&gt;=</span> <span class="va">ydstogo</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            percentage <span class="op">=</span> <span class="va">aggressive</span> <span class="op">/</span> <span class="va">total</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">total</span> <span class="op">&gt;=</span> <span class="fl">50</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">arrange</span><span class="op">(</span><span class="op">-</span><span class="va">percentage</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">tibble</span><span class="op">(</span><span class="va">aggressiveness</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 x 6
   passer_id  player_name  team  total aggressive percentage
   &lt;chr&gt;      &lt;chr&gt;        &lt;chr&gt; &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;
 1 00-0033077 D.Prescott   DAL      84         53      0.631
 2 00-0035228 K.Murray     ARI      60         37      0.617
 3 00-0036389 J.Hurts      PHI      65         40      0.615
 4 00-0033873 P.Mahomes    KC       93         56      0.602
 5 00-0034855 B.Mayfield   CLE      59         35      0.593
 6 00-0036971 T.Lawrence   JAX      78         46      0.590
 7 00-0036355 J.Herbert    LAC      87         51      0.586
 8 00-0035710 D.Jones      NYG      60         35      0.583
 9 00-0036212 T.Tagovailoa MIA      60         35      0.583
10 00-0026498 M.Stafford   LA       95         54      0.568
# ... with 20 more rows</code></pre>
</div>
</div>
<p>As you can see in the <code>tibble()</code> output of the results, Dak Prescott was the most aggressive quarterback in 3rd down passing situations in the 2021 season, passing to, our beyond, the line of gain just over 63% of the time.</p>
<p>After creating a new dataframe called <code>aggressiveness</code> from the 2021 play-by-play we originally collected using <code>data &lt;- nflreadr::load_pbp(2021)</code>, we use <code>group_by</code> to ensure that the data is being collected <em>per individual quarterback</em> via <code>passer_id.</code></p>
<p>After using the <code>group_by</code> function to lump data with each individual QB, we then use <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> function. Of course, we only want those <code>play_types</code> that are “pass” on 3rd downs. However, in the above code, we are filtering for <em>just</em>&nbsp;those 3rd down situations where the <code>yards to go</code> are between five and ten yards.</p>
<p>Doing so was a personal decision on my end when creating the metric, as there are certainly arguments to be made regarding how to “capture” scenarios in the data that require “aggressiveness.” My logic? If there were less than five yards to go on 3rd down, the opposing defense would not be able to “sell out” to the pass as it would not be out of the question for an offense to attempt to gain the first down on the ground. Conversely, anything <em>over</em> ten yards likely results in the defense selling out to the pass, thus leaving an imprint on the aggressiveness output of the quarterbacks.</p>
<p>For the sake of curiosity, we can edit the above code to include all passing attempts on 3rd down with under 10 yards to go for the first down:</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">aggressiveness.under.10</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer_id</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">down</span> <span class="op">==</span> <span class="fl">3</span>, <span class="va">play_type</span> <span class="op">==</span> <span class="st">"pass"</span>, <span class="va">ydstogo</span> <span class="op">&lt;=</span> <span class="fl">10</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>player_name <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">passer</span><span class="op">)</span>,</span>
<span>            team <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">posteam</span><span class="op">)</span>,</span>
<span>            total <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,</span>
<span>            aggressive <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">air_yards</span> <span class="op">&gt;=</span> <span class="va">ydstogo</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            percentage <span class="op">=</span> <span class="va">aggressive</span> <span class="op">/</span> <span class="va">total</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">total</span> <span class="op">&gt;=</span> <span class="fl">50</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">arrange</span><span class="op">(</span><span class="fu">desc</span><span class="op">(</span><span class="va">percentage</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">tibble</span><span class="op">(</span><span class="va">aggressiveness.under.10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 33 x 6
   passer_id  player_name  team  total aggressive percentage
   &lt;chr&gt;      &lt;chr&gt;        &lt;chr&gt; &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;
 1 00-0035228 K.Murray     ARI      98         67      0.684
 2 00-0036389 J.Hurts      PHI     107         73      0.682
 3 00-0036971 T.Lawrence   JAX     131         88      0.672
 4 00-0033077 D.Prescott   DAL     136         89      0.654
 5 00-0034857 J.Allen      BUF     138         88      0.638
 6 00-0036355 J.Herbert    LAC     148         94      0.635
 7 00-0036212 T.Tagovailoa MIA      93         59      0.634
 8 00-0026498 M.Stafford   LA      172        109      0.634
 9 00-0023459 A.Rodgers    GB      128         80      0.625
10 00-0035710 D.Jones      NYG      85         53      0.624
# ... with 23 more rows</code></pre>
</div>
</div>
<p>The results are quite different from the first running of this metric, as Dak Prescott is now the 4th most aggressive QB, while Kyler Murray moves to the top by approaching a nearly 70% aggressiveness rate on 3rd down. This small change highlights an important element about analytics: much of the work is the result of the coder (ie., <u>you</u>) being able to justify your decision-making process when developing the filters for each metric you create.</p>
<p>In this case, I stand by my argument that including just those pass attempts on 3rd down with between 5 and 10 yards to go is a more accurate assessment of aggressiveness as, for example, 3rd down with 8 yards to go is an obvious passing situation in <u>most</u> cases.</p>
<p>That begs the question, though: in which cases is 3rd down with 8 yards to go <u>not</u> an obvious passing situation? An example of this falls under the guise of “garbage time.”</p>
<section id="qb-aggressiveness-filtering-for-garbage-time" class="level4" data-number="4.2.1.1"><h4 data-number="4.2.1.1" class="anchored" data-anchor-id="qb-aggressiveness-filtering-for-garbage-time">
<span class="header-section-number">4.2.1.1</span> QB Aggressiveness: Filtering for “Garbage Time?”</h4>
<p>In our initial running of the QB Aggressiveness metric, Josh Allen is the 15th most aggressive QB in the NFL on 3rd down with between 5 and 10 yards to go. But how much does the success of the Buffalo Bills play into that 15th place ranking?</p>
<p>The Bills, at the conclusion of the 2021 season, had the largest positive point differential in the league at 194 (the Bills scored 483 points, while allowing just 289). Perhaps Allen’s numbers are skewed because the Bills were so often playing with the lead late into the game?</p>
<p>To account for this, we can add information into the <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> function to attempt to remove what are referenced to in the analytics community as “garbage time stats.”</p>
<p>Let’s add the “garbage time” filter to the code we’ve already prepared:</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">aggressiveness.garbage</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer_id</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">down</span> <span class="op">==</span> <span class="fl">3</span>, <span class="va">play_type</span> <span class="op">==</span> <span class="st">"pass"</span>, <span class="va">ydstogo</span> <span class="op">&gt;=</span> <span class="fl">5</span>, <span class="va">ydstogo</span> <span class="op">&lt;=</span> <span class="fl">10</span>,</span>
<span>         <span class="va">wp</span> <span class="op">&gt;</span> <span class="fl">.05</span>, <span class="va">wp</span> <span class="op">&lt;</span> <span class="fl">.95</span>, <span class="va">half_seconds_remaining</span> <span class="op">&gt;</span> <span class="fl">120</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>player_name <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">passer</span><span class="op">)</span>,</span>
<span>            team <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">posteam</span><span class="op">)</span>,</span>
<span>            total <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,</span>
<span>            aggressive <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">air_yards</span> <span class="op">&gt;=</span> <span class="va">ydstogo</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            percentage <span class="op">=</span> <span class="va">aggressive</span> <span class="op">/</span> <span class="va">total</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">total</span> <span class="op">&gt;=</span> <span class="fl">50</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">arrange</span><span class="op">(</span><span class="fu">desc</span><span class="op">(</span><span class="va">percentage</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">tibble</span><span class="op">(</span><span class="va">aggressiveness.garbage</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 26 x 6
   passer_id  player_name team  total aggressive percentage
   &lt;chr&gt;      &lt;chr&gt;       &lt;chr&gt; &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;
 1 00-0033077 D.Prescott  DAL      61         40      0.656
 2 00-0036971 T.Lawrence  JAX      51         33      0.647
 3 00-0035228 K.Murray    ARI      51         31      0.608
 4 00-0026498 M.Stafford  LA       79         48      0.608
 5 00-0033873 P.Mahomes   KC       68         41      0.603
 6 00-0035710 D.Jones     NYG      50         30      0.6  
 7 00-0036355 J.Herbert   LAC      67         38      0.567
 8 00-0036972 M.Jones     NE       57         31      0.544
 9 00-0034857 J.Allen     BUF      59         32      0.542
10 00-0029263 R.Wilson    SEA      56         30      0.536
# ... with 16 more rows</code></pre>
</div>
</div>
<p>We are now using the same code, but have included three new items to the <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code>. First, we are stipulating that, aside from the down and distance inclusion, we only want those plays that occurred when the offense’s <code>win probability</code> was between 5% and 95%, as well as ensuring that the plays did not happen after the two-minute warning of either half.</p>
<p>The decision on range of the <code>win probability</code> numbers is, again, a personal preference. When <code>nflfastR</code> was first released, analyst often used a 20-80% range for <code>win probability</code>. However, Sebastian Carl - one of the creators of the <code>nflverse</code> explained in the package’s Discord:</p>
<blockquote class="blockquote">
<p>Sebastian Carl: “I am generally very conservative with filtering plays using wp. Especially the vegas wp model can reach &gt;85% probs early in the game because it incorporates market lines. I never understood the 20% &lt;= wp &lt;= 80%”garbage time” filter. This is removing a ton of plays. My general advice is a lower boundary of something around 5% (i.e., 5% &lt;= wp &lt;= 95%).</p>
</blockquote>
<p>Ben Baldwin followed up on Carl’s thoughts:</p>
<blockquote class="blockquote">
<p>Ben Baldwin: “agree with this. 20-80% should only be used as a filter for looking at how run-heavy a team is (because outside of this range is when teams change behavior a lot). and possibly how teams behave on 4th downs. but not for team or player performance.”</p>
</blockquote>
<p>Based on that advice, I typically stick to the 5-95% range when filtering for <code>win probability</code> using play-by-play data. And, in this case, it did have an impact.</p>
<p>As mentioned, prior to filtering for garbage time, Allen was the 15th most aggressive QB in the league at nearly 52%. However, once filtering for garbage time, Allen rose to 9th most aggressive QB, with a slight increase of percentage to 54%.</p>
<p>What is interesting about the above example, though, is Dak Prescott and the Cowboys. Dallas maintained the second largest point differential in the league (530 points for and 358 points against, for a 172 point difference). Without the garbage time filter, Prescott was tops in the NFL with an aggressiveness rating of 63%.</p>
<p>Once adjusted for garbage time? Prescott remained atop the NFL with an aggressiveness rating of 65.5%.</p>
<p>Allen’s increase in the standings, and Prescott remaining best in the league, in this specific metric, is a possible indicator that the inclusion of the “garbage time” filters provides a slightly more accurate result.</p>
</section></section><section id="the-inclusion-of-contextual-statistics" class="level3" data-number="4.2.2"><h3 data-number="4.2.2" class="anchored" data-anchor-id="the-inclusion-of-contextual-statistics">
<span class="header-section-number">4.2.2</span> The Inclusion of Contextual Statistics</h3>
<p>As seen in the above example regarding QB aggressiveness on 3rd down, the using of the <code>load_pbp()</code> function provides the ability to create situation specific metrics that would otherwise be lost in aggregated weekly statistics.</p>
</section></section><section id="retrieving-working-with-data-for-multiple-seasons" class="level2" data-number="4.3"><h2 data-number="4.3" class="anchored" data-anchor-id="retrieving-working-with-data-for-multiple-seasons">
<span class="header-section-number">4.3</span> Retrieving &amp; Working With Data for Multiple Seasons</h2>
<p>In the case of both <code>load_pbp()</code> and <code>load_player_stats()</code>, it is possible to load data over multiple seasons.</p>
<p>In our above example calculating average air yard per attempt, it is important to note that Russell Wilson’s league-leading average of 9.89 air yards per attempt is calculated using <em>all</em> passing attempts, meaning pass attempts that were both complete and incomplete.</p>
<p>In our first example of working with data across multiple seasons, let’s examine average air yards for only completed passes. To begin, we will retrieve the play-by-play data for the last five seasons:</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ay.five.years</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_pbp.html">load_pbp</a></span><span class="op">(</span><span class="fl">2017</span><span class="op">:</span><span class="fl">2021</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To retrieve multiple seasons of data, a colon <code>:</code> is placed between the years that you want. When you run the code, <code>nflreadr</code> will output the data to include the play-by-play data starting with the oldest season (in this case, the 2017 NFL season).</p>
<p>Once you have the data collected, we can run code that looks quite similar to our code above that explored 2021’s air yards per attempt leaders using <code>load_player_stats()</code>. In this case, however, we are including an additional filter to gather those passing attempts that resulted <em>only</em> in complete passes:</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">average.airyards</span> <span class="op">&lt;-</span> <span class="va">ay.five.years</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer_id</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span> <span class="op">&amp;</span> <span class="va">complete_pass</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>player <span class="op">=</span> <span class="fu">first</span><span class="op">(</span><span class="va">passer_player_name</span><span class="op">)</span>,</span>
<span>            completions <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">complete_pass</span><span class="op">)</span>,</span>
<span>            air.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">air_yards</span><span class="op">)</span>,</span>
<span>            average <span class="op">=</span> <span class="va">air.yards</span> <span class="op">/</span> <span class="va">completions</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">completions</span> <span class="op">&gt;=</span> <span class="fl">1000</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">arrange</span><span class="op">(</span><span class="op">-</span><span class="va">average</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">tibble</span><span class="op">(</span><span class="va">average.airyards</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 22 x 5
   passer_id  player      completions air.yards average
   &lt;chr&gt;      &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
 1 00-0031503 J.Winston          1008      8174    8.11
 2 00-0033537 D.Watson           1186      8461    7.13
 3 00-0029263 R.Wilson           1603     10939    6.82
 4 00-0026143 M.Ryan             1954     13051    6.68
 5 00-0034855 B.Mayfield         1185      7858    6.63
 6 00-0034857 J.Allen            1245      8221    6.60
 7 00-0033077 D.Prescott         1613     10449    6.48
 8 00-0026498 M.Stafford         1668     10804    6.48
 9 00-0029701 R.Tannehill        1049      6680    6.37
10 00-0032950 C.Wentz            1505      9491    6.31
# ... with 12 more rows</code></pre>
</div>
</div>
<p>Of those QBs with at least 1,000 complete passes since the 2017 season, Jameis Winston has the highest average air yards per complete pass at 8.11.</p>
</section><section id="working-with-the-various-nflreadr-functions" class="level2" data-number="4.4"><h2 data-number="4.4" class="anchored" data-anchor-id="working-with-the-various-nflreadr-functions">
<span class="header-section-number">4.4</span> Working with the Various <code>nflreadr</code> Functions</h2>
<p>The <code>nflreadr</code> package comes with a multitude of “under the hood” functions designed to provide you with supplemental data, items for data visualization, and utilities for efficiently collecting and storing the data on your system. You can view the entire list of these options using the <code>ls</code> to output all the objects in the package.</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="st">"package:nflreadr"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "clean_homeaway"               "clean_player_names"          
 [3] "clean_team_abbrs"             "clear_cache"                 
 [5] "csv_from_url"                 "dictionary_combine"          
 [7] "dictionary_contracts"         "dictionary_depth_charts"     
 [9] "dictionary_draft_picks"       "dictionary_espn_qbr"         
[11] "dictionary_ff_opportunity"    "dictionary_ff_playerids"     
[13] "dictionary_ff_rankings"       "dictionary_injuries"         
[15] "dictionary_nextgen_stats"     "dictionary_participation"    
[17] "dictionary_pbp"               "dictionary_pfr_passing"      
[19] "dictionary_player_stats"      "dictionary_rosters"          
[21] "dictionary_schedules"         "dictionary_snap_counts"      
[23] "dictionary_trades"            "ffverse_sitrep"              
[25] "get_current_season"           "get_current_week"            
[27] "get_latest_season"            "join_coalesce"               
[29] "load_combine"                 "load_contracts"              
[31] "load_depth_charts"            "load_draft_picks"            
[33] "load_espn_qbr"                "load_ff_opportunity"         
[35] "load_ff_playerids"            "load_ff_rankings"            
[37] "load_from_url"                "load_injuries"               
[39] "load_nextgen_stats"           "load_officials"              
[41] "load_participation"           "load_pbp"                    
[43] "load_pfr_advstats"            "load_pfr_passing"            
[45] "load_player_stats"            "load_players"                
[47] "load_rosters"                 "load_rosters_weekly"         
[49] "load_schedules"               "load_snap_counts"            
[51] "load_teams"                   "load_trades"                 
[53] "most_recent_season"           "nflverse_download"           
[55] "nflverse_game_id"             "nflverse_releases"           
[57] "nflverse_sitrep"              "parquet_from_url"            
[59] "player_name_mapping"          "progressively"               
[61] "qs_from_url"                  "raw_from_url"                
[63] "rbindlist_with_attrs"         "rds_from_url"                
[65] "team_abbr_mapping"            "team_abbr_mapping_norelocate"</code></pre>
</div>
</div>
<p>Going forward in this chapter, we will be exploring specific use cases for the functions provided by <code>nflreadr</code> - but not all of them. For example, the <code>dictionary_</code> functions can more easily be used directly on the <code>nflreadr</code> website where the package’s maintainers keep a copy of each. Many, like the dictionary for play-by-play data, includes a search feature to allow you to quickly find how the variables you are looking for is provided in the column name. Others, like the <code>clear_cache()</code> function is used only when you want to wipe any memoized data stored by <code>nflreadr</code> - often needed if you are troubleshooting a pesky error message - <code>join_coalesce()</code> which is an experimental function that is only used internally to help build player IDs into the data. The <code>load_pbp()</code> and <code>load_player_stats()</code> function will also not be covered here, as the first portion of this chapter explored the use of both in great detail. We will briefly discuss the use of <code>load_players()</code> and <code>load_rosters()</code> but a more detailed discussion of each is provided in Chapter 4: Data Visualization with NFL Analytics. The remaining functions will be presented in the order provided on the <a href="https://nflreadr.nflverse.com/reference/index.html"><code>nflreadr</code> function reference website.</a></p>
<section id="the-load_participation-function" class="level3" data-number="4.4.1"><h3 data-number="4.4.1" class="anchored" data-anchor-id="the-load_participation-function">
<span class="header-section-number">4.4.1</span> The <code>load_participation()</code> Function</h3>
<p>The <code>load_participation()</code> function allows us to create a dataframe of player participation data dating back to 2016 with an option to infuse that information into the existing <code>nflreadr</code> play-by-play data. The resulting dataframe, when not including play-by-play data, includes information pertaining to: the individial game ID, the play ID, the possession team, what formation the offense was in, the layout of the offensive personnel, how many defenders were in the box, the defensive personnel, the number of rushers on pass players, and the unique ID number for each player on the field for that specific play.</p>
<p>Despite the <code>load_participation()</code> function being one of the newest editions to the <code>nflreadr</code> package, it is already being used to create contextual analysis regarding a team’s use of its players out out formations. For example, <a href="https://twitter.com/josephjefe">Joseph Hefner</a> uses the data to create tables (built with the <code>gt</code> packages) that calculates not only each player’s rate of usage out of different personnel packages, but how the team’s EPA per play and pass rate fluncuate with each. In the spirit of R’s open-source nature, he also created a <a href="https://josephjefe.shinyapps.io/formations_app/">Team Formation ShinyApp</a> that allows anybody to explore the data and output the results in .png format.</p>
<p></p>
<div id="tweet-99582"></div>
<script>tweet={"url":"https:\/\/twitter.com\/josephjefe\/status\/1621217561437409280","author_name":"Joseph Hefner","author_url":"https:\/\/twitter.com\/josephjefe","html":"\u003Cblockquote class=\"twitter-tweet\" align=\"center\"\u003E\u003Cp lang=\"en\" dir=\"ltr\"\u003EFormations from KC vs CIN! Chiefs offense first. Our 11 personnel was very not great. Probably due to all the attrition. But the other formations were pretty spectacular. Look at that 3TE 2WR set!!! Reid is a wizard. \u003Ca href=\"https:\/\/twitter.com\/hashtag\/nflverse?src=hash&amp;ref_src=twsrc%5Etfw\"\u003E#nflverse\u003C\/a\u003E \u003Ca href=\"https:\/\/twitter.com\/hashtag\/rstats?src=hash&amp;ref_src=twsrc%5Etfw\"\u003E#rstats\u003C\/a\u003E \u003Ca href=\"https:\/\/t.co\/UR87Wdu0mG\"\u003Epic.twitter.com\/UR87Wdu0mG\u003C\/a\u003E\u003C\/p\u003E&mdash; Joseph Hefner (@josephjefe) \u003Ca href=\"https:\/\/twitter.com\/josephjefe\/status\/1621217561437409280?ref_src=twsrc%5Etfw\"\u003EFebruary 2, 2023\u003C\/a\u003E\u003C\/blockquote\u003E\n\u003Cscript async src=\"https:\/\/platform.twitter.com\/widgets.js\" charset=\"utf-8\"\u003E\u003C\/script\u003E\n","width":550,"height":null,"type":"rich","cache_age":"3153600000","provider_name":"Twitter","provider_url":"https:\/\/twitter.com","version":"1.0"};document.getElementById("tweet-99582").innerHTML = tweet["html"];</script><p>To build a dataframe of 2022 participation data, that includes complete play-by-play, you must pass both the <code>season</code> and <code>include_pbp</code> argument with the <code>load_participation()</code> function.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">participation</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_participation.html">load_participation</a></span><span class="op">(</span>season <span class="op">=</span> <span class="fl">2022</span>, include_pbp <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">participation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 49,969 x 383
   nflverse_ga~1 play_id posse~2 offen~3 offen~4 defen~5 defen~6 numbe~7 playe~8
   &lt;chr&gt;           &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;int&gt; &lt;chr&gt;     &lt;int&gt; &lt;chr&gt;  
 1 2022_01_BAL_~       1 ""      &lt;NA&gt;    &lt;NA&gt;         NA &lt;NA&gt;         NA ""     
 2 2022_01_BAL_~      43 "BAL"   &lt;NA&gt;    &lt;NA&gt;         NA &lt;NA&gt;         NA "47969~
 3 2022_01_BAL_~      68 "NYJ"   SINGLE~ 1 RB, ~       7 3 DL, ~      NA "53536~
 4 2022_01_BAL_~      89 "NYJ"   SHOTGUN 1 RB, ~       6 3 DL, ~       4 "53536~
 5 2022_01_BAL_~     115 "NYJ"   SINGLE~ 1 RB, ~       7 3 DL, ~      NA "53536~
 6 2022_01_BAL_~     136 "NYJ"   SHOTGUN 1 RB, ~       7 3 DL, ~       4 "53536~
 7 2022_01_BAL_~     172 "NYJ"   &lt;NA&gt;    &lt;NA&gt;         NA &lt;NA&gt;         NA "53059~
 8 2022_01_BAL_~     202 "BAL"   SINGLE~ 2 RB, ~       7 4 DL, ~       3 "44929~
 9 2022_01_BAL_~     230 "BAL"   SHOTGUN 2 RB, ~       6 4 DL, ~       3 "44929~
10 2022_01_BAL_~     254 "BAL"   EMPTY   1 RB, ~       5 4 DL, ~      NA "44929~
# ... with 49,959 more rows, 374 more variables: offense_players &lt;chr&gt;,
#   defense_players &lt;chr&gt;, n_offense &lt;int&gt;, n_defense &lt;int&gt;, old_game_id &lt;chr&gt;,
#   home_team &lt;chr&gt;, away_team &lt;chr&gt;, season_type &lt;chr&gt;, week &lt;int&gt;,
#   posteam &lt;chr&gt;, posteam_type &lt;chr&gt;, defteam &lt;chr&gt;, side_of_field &lt;chr&gt;,
#   yardline_100 &lt;dbl&gt;, game_date &lt;chr&gt;, quarter_seconds_remaining &lt;dbl&gt;,
#   half_seconds_remaining &lt;dbl&gt;, game_seconds_remaining &lt;dbl&gt;,
#   game_half &lt;chr&gt;, quarter_end &lt;dbl&gt;, drive &lt;dbl&gt;, sp &lt;dbl&gt;, qtr &lt;dbl&gt;, ...</code></pre>
</div>
</div>
<p>Rather than exploring the data at the league-level, let’s take a micro-approach to the participation data and examine the the 2022 Pittsburgh Steelers. It is important to note that the participation data, as gathered using the <code>load_participation()</code> function, is not fully prepped for immediate analysis as the <code>players_on_play</code>, <code>offense_players</code>, and <code>defense_players</code> information (which contains the unique player indentification numbers) are separated by a delimiter (in this case, a semicolon) in what are called “concatenated strings” or “delimited strings.” While this is a compact way to store the values in the core dataframe, it does require us to clean the information through the “splitting” or “tokenizing” process. As you will see in the below code, we are going to place the unique identifiers into separate rows, based on formation, by utilizing the <code>separate_rows()</code> function in <code>tidyr</code>.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you use <code>load_participation()</code> but set <code>include_pbp = FALSE</code> it is important to remember that the <code>posteam</code> variable that is part of the play-by-play data will not exist. Instead, the offensive team is indicated by the <code>possession_team</code> column.</p>
<p>If you gather the participation data <em>with</em> play-by-play information, you can use either <code>possession_team</code> or <code>posteam</code> for any filtering.</p>
<p>The same is not true when looking at defensive participation data. A defensive team variable is not provided without included the play-by-play in the data. Once set to <code>TRUE</code>, the defensive team is housed under the typical <code>defteam</code> column.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">participation_split</span> <span class="op">&lt;-</span> <span class="va">participation</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">offense_formation</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">posteam</span> <span class="op">==</span> <span class="st">"PIT"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">tidyr</span><span class="fu">::</span><span class="fu"><a href="https://tidyr.tidyverse.org/reference/separate_rows.html">separate_rows</a></span><span class="op">(</span><span class="va">offense_players</span>, sep <span class="op">=</span> <span class="st">";"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">offense_personnel</span>, <span class="va">offense_players</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>total <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">ungroup</span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">participation_split</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 157 x 3
   offense_personnel offense_players total
   &lt;chr&gt;             &lt;chr&gt;           &lt;int&gt;
 1 1 RB, 1 TE, 3 WR  00-0032897          3
 2 1 RB, 1 TE, 3 WR  00-0033869        262
 3 1 RB, 1 TE, 3 WR  00-0034142         37
 4 1 RB, 1 TE, 3 WR  00-0034347        781
 5 1 RB, 1 TE, 3 WR  00-0034768        781
 6 1 RB, 1 TE, 3 WR  00-0034785        744
 7 1 RB, 1 TE, 3 WR  00-0034928        235
 8 1 RB, 1 TE, 3 WR  00-0035216        745
 9 1 RB, 1 TE, 3 WR  00-0035217         25
10 1 RB, 1 TE, 3 WR  00-0035222        258
# ... with 147 more rows</code></pre>
</div>
</div>
<p>We are doing quite a few things in the above example:</p>
<ol type="1">
<li>
<strong>Those rows where the is an ‘NA’ value for <code>offense_formation</code></strong> <strong>are removed.</strong> The participation data includes information for kickoffs, extra points, field goals, punts, QB kneels, no plays, and more. It is possible to remove items using <code>play_type == "run" | play_type == "pass"</code> but such an approach, if done with the Steelers, results in one fake punt being included in the data (as the <code>play_type</code> was listed as “run”). If you wish to include plays such as fake punts, you do so by filtering for only specific play types.</li>
<li>
<strong>Only those rows that includes ‘PIT’ as the <code>posteam</code></strong> <strong>are included.</strong>
</li>
<li>
<strong>The <code>separate_rows()</code></strong> <strong>function from <code>tidyr</code></strong> <strong>is used to conduct the splitting of the concatenated players identifiers in the <code>offense_players</code></strong> <strong>column</strong>. The <code>separate_rows()</code> function needs just to arguments to complete the process - the column name and the delimiter (provided in the argument as <code>sep =</code>).</li>
<li>
<strong>The newly split data is then grouped by <code>offense_personnel</code></strong> <strong>and <code>offense_players</code></strong> <strong>in order to calculate the number of times each specific ID was associated with personnel package</strong>. The resulting dataframe lists the offense formation type for each player that participated in it, along with the player’s respective participation count.</li>
</ol>
<p>As is, the <code>load_participation()</code> data does not include any way to further identify players outside of the unique players IDs. Because of this, it is necessary to use the <code>load_rosters()</code> function to include this information (this process is included below in the <code>load_rosters()</code> section).</p>
</section><section id="the-load_rosters-and-load_rosters_weekly-functions" class="level3" data-number="4.4.2"><h3 data-number="4.4.2" class="anchored" data-anchor-id="the-load_rosters-and-load_rosters_weekly-functions">
<span class="header-section-number">4.4.2</span> The <code>load_rosters()</code> and <code>load_rosters_weekly()</code> Functions</h3>
<p>The <code>load_rosters()</code> function houses a multitude of useful tools for use in the <code>nflverse</code>. With player information dating back to 1920, <code>load_rosters()</code> will provide you with basic demographic information about each player in the NFL such as their name, birth date, height, weight, the college and high school they attended, and items regarding primary position and depth chart position.</p>
<p>Importantly, <code>load_rosters()</code> also provides the unique identifier for each player over nine different sources: the <code>gsis_id</code> (which is the core ID used in <code>nflverse</code> data), <code>sleeper_id</code>, <code>espn_id</code>, <code>yahoo_id</code>, <code>rotowire_id</code>, <code>pff_id</code>, <code>fantasy_data_id</code>, <code>sportradar_id</code>, and <code>pfr_id</code>. The different IDs become extremely useful when using data collected from outside the <code>nflverse</code>, or when combining data from two outside sources, matching the information can be done by matching the various IDs as needed. As well, as outlined in Chapter 4: Data Visualization with NFL Analytics, the URLs for player headshots are included in <code>load_rosters()</code> data.</p>
<p>Let’s return to our <code>participation_split</code> dataframe that we built prior in this chapter while working with the <code>load_participation()</code> function. The the data is formatted and prepared for analysis, there is no information that allows for easy identification of each player (aside from unique IDs, which is not helpful). To correct this, we can bring in the 2022 Pittsburgh Steelers roster information.</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">rosters</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_rosters.html">load_rosters</a></span><span class="op">(</span><span class="fl">2022</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The only argument you must provide the <code>load_rosters()</code> function is the years in which you want to collect roster information (in this specific case, 2022). While we know we only want the Steelers’ roster, it is not suggested to use <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> to gather any specific team at this point. Case in point: do so with this example will result in the <code>gsis_id</code> <em>00-0036326</em> having an “NA” value for a name, despite having over 380 snaps in the 1 RB, 1TE, 3 WR offensive formation. The player associated with that <code>gsis_id</code> is Chase Claypool, who the Steelers traded to the Bears on November 1 of 2022. Because of this, no player name will be associated with that specific <code>gsis_id</code> on the Steelers’ roster (with the end result being a missing value).</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>You may notice that the resulting dataframe, titled <code>pit_roster</code>, has 80 players on the roster despite NFL teams only being permitted to have 53 active players at a time.</p>
<p>This is because the information collected with <code>load_rosters()</code> includes not only active players, but those listed on the practice squad and injured reserve. Additionally, you may notice players listed as <code>R/Retired</code> (such as Stephon Tuitt in our dataframe, who retired at the end of the 2022 season). In these situations, this <code>status</code> indicated that the player is listed as ‘reserved-retired’ and that the team continues to hold the player’s rights until the official expiration of their contract. In this case, Tuitt could not come out of retirement prior to his contract ending and play with another team unless first released or traded by Pittsburgh.</p>
</div>
</div>
<p>Despite the wealth of information in the roster information, only the <code>gsis_id</code> and the <code>full_name</code> is required to complete our <code>participation_split</code> dataframe. Rather than bringing unnecessary information over during the merge, we can select just the two columns we need and then use <code>left_join()</code> to merge each player’s name on the matching ID in the <code>offense_players</code> column and <code>gsis_id</code> from the roster information.</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">rosters</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_rosters.html">load_rosters</a></span><span class="op">(</span><span class="fl">2022</span><span class="op">)</span></span>
<span></span>
<span><span class="va">rosters</span> <span class="op">&lt;-</span> <span class="va">rosters</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">gsis_id</span>, <span class="va">full_name</span><span class="op">)</span></span>
<span></span>
<span><span class="va">participation_split</span> <span class="op">&lt;-</span> <span class="va">participation_split</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span><span class="va">rosters</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"offense_players"</span> <span class="op">=</span> <span class="st">"gsis_id"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">participation_split</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 157 x 4
   offense_personnel offense_players total full_name        
   &lt;chr&gt;             &lt;chr&gt;           &lt;int&gt; &lt;chr&gt;            
 1 1 RB, 1 TE, 3 WR  00-0032897          3 Derek Watt       
 2 1 RB, 1 TE, 3 WR  00-0033869        262 Mitchell Trubisky
 3 1 RB, 1 TE, 3 WR  00-0034142         37 J.C. Hassenauer  
 4 1 RB, 1 TE, 3 WR  00-0034347        781 James Daniels    
 5 1 RB, 1 TE, 3 WR  00-0034768        781 Chukwuma Okorafor
 6 1 RB, 1 TE, 3 WR  00-0034785        744 Mason Cole       
 7 1 RB, 1 TE, 3 WR  00-0034928        235 Steven Sims      
 8 1 RB, 1 TE, 3 WR  00-0035216        745 Diontae Johnson  
 9 1 RB, 1 TE, 3 WR  00-0035217         25 Benny Snell      
10 1 RB, 1 TE, 3 WR  00-0035222        258 Zach Gentry      
# ... with 147 more rows</code></pre>
</div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>load_rosters()</code> data is capable of providing data for multiple seasons at once. Through each season, a player’s <code>gsis_id</code> will remain static. Despite this, when merging multiple years of participation data with multiple years of roster information, the data must be matched on the <code>season</code> variable was well. This process involves including <code>season</code> in both the participation data <code>group_by()</code> and the roster information, as seen below.</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">participation_multi_years</span> <span class="op">&lt;-</span> <span class="fu">load_participation</span><span class="op">(</span>season <span class="op">=</span> <span class="fl">2018</span><span class="op">:</span><span class="fl">2022</span>, include_pbp <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">participation_2018_2022</span> <span class="op">&lt;-</span> <span class="va">participation_multi_years</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">offense_formation</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">posteam</span> <span class="op">==</span> <span class="st">"PIT"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">tidyr</span><span class="fu">::</span><span class="fu"><a href="https://tidyr.tidyverse.org/reference/separate_rows.html">separate_rows</a></span><span class="op">(</span><span class="va">offense_players</span>, sep <span class="op">=</span> <span class="st">";"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">season</span>, <span class="va">offense_personnel</span>, <span class="va">offense_players</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>total <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">rosters_2018_2022</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_rosters.html">load_rosters</a></span><span class="op">(</span><span class="fl">2018</span><span class="op">:</span><span class="fl">2022</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">season</span>, <span class="va">gsis_id</span>, <span class="va">full_name</span><span class="op">)</span></span>
<span></span>
<span><span class="va">participation_2018_2022</span> <span class="op">&lt;-</span> <span class="va">participation_2018_2022</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span><span class="va">rosters_2018_2022</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"season"</span>, <span class="st">"offense_players"</span> <span class="op">=</span> <span class="st">"gsis_id"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>If your analysis requires providing great granularity, the <code>load_rosters_weekly()</code> function provides the same information as <code>load_rosters()</code> but structures it in weekly format by season (or over multiple seasons, if needed).</p>
</section><section id="the-load_teams-function" class="level3" data-number="4.4.3"><h3 data-number="4.4.3" class="anchored" data-anchor-id="the-load_teams-function">
<span class="header-section-number">4.4.3</span> The <code>load_teams()</code> Function</h3>
<p>A tool heavily used in the data vizualization process, the <code>load_teams()</code> function provides information pertaining to each NFL team’s colors and logos, as well as providing a way to merge dataframes that have differing values for teams. The</p>
</section><section id="the-load_schedules-function" class="level3" data-number="4.4.4"><h3 data-number="4.4.4" class="anchored" data-anchor-id="the-load_schedules-function">
<span class="header-section-number">4.4.4</span> The <code>load_schedules()</code> Function</h3>
<p>fffff</p>
</section><section id="the-load_officials-function" class="level3" data-number="4.4.5"><h3 data-number="4.4.5" class="anchored" data-anchor-id="the-load_officials-function">
<span class="header-section-number">4.4.5</span> The <code>load_officials()</code> Function</h3>
<p>The <code>load_officials()</code> data will return data, from 2015 to present, outlining which officials were assigned to which game. The data also includes information regarding each referee’s position, jersey number, and their official NFL ID number. Importantly, the data is structured to also include both a <code>game_id</code> and <code>game_key</code> that are sorted by <code>season</code> and <code>week</code>, allowing you to merge the information other dataframes.</p>
<p>With the data, we can - for example - examine which NFL officiating crews called the most penalties during the 2022 NFL season. Doing so requires a bit of work in order to assign a unique <code>crew_id</code> to each stable of officials “working” under a lead referee.</p>
<p>As an example, we can create data frame called <code>nfl_officials</code> that contains the official and referee information for each game during the 2022 season. After, in order to get the referee for each crew, use <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> to select those crew members with the “Referee” position and then create a new column titled <code>crew_id</code> that takes the numeric official ID for each distinct Referee.</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nfl_officials</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_officials.html">load_officials</a></span><span class="op">(</span>seasons <span class="op">=</span> <span class="fl">2022</span><span class="op">)</span></span>
<span></span>
<span><span class="va">referees</span> <span class="op">&lt;-</span> <span class="va">nfl_officials</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">position</span> <span class="op">==</span> <span class="st">"Referee"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>crew_id <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/match.html">match</a></span><span class="op">(</span><span class="va">official_id</span>, <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">official_id</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>With a unique <code>crew_id</code> associated with each Referee, we can now use <code>left_join()</code> to bring that information back into our <code>nfl_officials</code> data by merging the <code>game_id</code> and <code>crew_id</code> to the corresponding <code>game_id</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nfl_officials</span> <span class="op">&lt;-</span> <span class="va">nfl_officials</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span><span class="va">referees</span> <span class="op">%&gt;%</span> <span class="fu">select</span><span class="op">(</span><span class="va">game_id</span>, <span class="va">crew_id</span><span class="op">)</span>, by <span class="op">=</span> <span class="st">"game_id"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The resulting <code>nfl_officials</code> data frame now includes all the original information and now a consistent <code>crew_id</code> for each team that the referee works with.</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nfl_officials</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,065 x 10
   game_id  game_~1 offic~2 posit~3 jerse~4 offic~5 season seaso~6  week crew_id
   &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;     &lt;int&gt; &lt;chr&gt;    &lt;int&gt; &lt;chr&gt;   &lt;int&gt;   &lt;int&gt;
 1 2022090~ 58838   Nathan~ Field ~      42 174       2022 REG         1       1
 2 2022090~ 58838   Matt E~ Back J~      96 178       2022 REG         1       1
 3 2022090~ 58838   Mike C~ Down J~      63 168       2022 REG         1       1
 4 2022090~ 58838   Eugene~ Side J~     103 108       2022 REG         1       1
 5 2022090~ 58838   Jeff S~ Line J~      45 23        2022 REG         1       1
 6 2022090~ 58838   Carl C~ Referee      51 3         2022 REG         1       1
 7 2022090~ 58838   Brando~ Umpire        0 201       2022 REG         1       1
 8 2022091~ 58839   Mike M~ Umpire        0 206       2022 REG         1       2
 9 2022091~ 58839   John J~ Field ~     117 86        2022 REG         1       2
10 2022091~ 58839   Danny ~ Down J~     113 172       2022 REG         1       2
# ... with 2,055 more rows, and abbreviated variable names 1: game_key,
#   2: official_name, 3: position, 4: jersey_number, 5: official_id,
#   6: season_type</code></pre>
</div>
</div>
<p>To calculate the total number of penalties flagged by each crew, we must first bring in the play-by-play from the 2022 season. After, we will use <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> to gather only those plays where a flag was thrown, and then <code>select()</code> the relevant columns, and finally <code>summarize()</code> by the <code>old_game_id</code> to get the total penalties called and the total penalty yards as a result of those penalties.</p>
<p>After, we conducted another <code>left_join()</code> to bring in the specific penalty information into our <code>nfl_officials</code> data frame.</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">penalty_pbp</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_pbp.html">load_pbp</a></span><span class="op">(</span>seasons <span class="op">=</span> <span class="fl">2022</span><span class="op">)</span></span>
<span></span>
<span><span class="va">penalties</span> <span class="op">&lt;-</span> <span class="va">penalty_pbp</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">penalty</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">game_id</span>, <span class="va">old_game_id</span>, <span class="va">season</span>, <span class="va">play_id</span>, <span class="va">desc</span>, <span class="va">home_team</span>, <span class="va">away_team</span>,</span>
<span>         <span class="va">posteam</span>, <span class="va">defteam</span>, <span class="va">week</span>, <span class="va">penalty_team</span>, <span class="va">penalty_type</span>, <span class="va">penalty</span>, <span class="va">penalty_player_id</span>,</span>
<span>         <span class="va">penalty_player_name</span>, <span class="va">penalty_yards</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">old_game_id</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>total_called <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">penalty</span> <span class="op">==</span> <span class="fl">1</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            total_yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">penalty_yards</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">nfl_officials</span> <span class="op">&lt;-</span> <span class="va">nfl_officials</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span><span class="va">penalties</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"game_id"</span> <span class="op">=</span> <span class="st">"old_game_id"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">game_id</span>, <span class="va">official_name</span>, <span class="va">position</span>, <span class="va">crew_id</span>, <span class="va">total_called</span>, <span class="va">total_yards</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>With the data now combined, we can <code>group_by()</code> each game’s unique <code>game_id</code> and then use <code>summarize()</code> to sum the penalties called and the penalty yardage. After descending by the total number of penalties, we can see that Referee Carl Cheffers, and his crew, called the most penalties during the 2022 NFL season with 223 and, unsurprisingly, also had the highest amount of penalty yards with 1,916.</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">nfl_officials</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">game_id</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">position</span> <span class="op">==</span> <span class="st">"Referee"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">ungroup</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">crew_id</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>referee <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">official_name</span><span class="op">)</span>,</span>
<span>            all_pen <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">total_called</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            all_yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">total_yards</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">arrange</span><span class="op">(</span><span class="fu">desc</span><span class="op">(</span><span class="va">all_pen</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">slice</span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">10</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 x 4
   crew_id referee        all_pen all_yards
     &lt;int&gt; &lt;chr&gt;            &lt;int&gt;     &lt;dbl&gt;
 1       1 Carl Cheffers      223      1916
 2      11 Scott Novak        204      1584
 3       6 Brad Allen         203      1511
 4      16 Clete Blakeman     203      1562
 5       5 Shawn Hochuli      199      1780
 6       4 Clay Martin        198      1684
 7      17 Adrian Hill        193      1564
 8       2 Alex Kemp          192      1602
 9      10 Tra Blake          189      1545
10      15 Ronald Torbert     185      1549</code></pre>
</div>
</div>
</section><section id="the-load_trades-function" class="level3" data-number="4.4.6"><h3 data-number="4.4.6" class="anchored" data-anchor-id="the-load_trades-function">
<span class="header-section-number">4.4.6</span> The <code>load_trades()</code> Function</h3>
<p>The <code>load_trades()</code> function returns a data frames that includes all trades in the NFL on a season-by-season basis with information pertaining to: <code>trade_id</code>, <code>season</code>, <code>trade_date</code>, <code>gave</code>, <code>received</code>, <code>pick_season</code>, <code>pick_round</code>, <code>pick_number</code>, <code>conditional</code>, <code>pfr_id</code>, <code>pfr_name</code>.</p>
<p>For example, we can gather every trade involving the New England Patriots with the following code:</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ne_trades</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_trades.html">load_trades</a></span><span class="op">(</span>seasons <span class="op">=</span> <span class="fl">2000</span><span class="op">:</span><span class="fl">2022</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">gave</span> <span class="op">==</span> <span class="st">"NE"</span> <span class="op">|</span> <span class="va">received</span> <span class="op">==</span> <span class="st">"NE"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ne_trades</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 498 x 11
   trade_id season trade_date gave  received pick_season pick_~1 pick_~2 condi~3
      &lt;dbl&gt;  &lt;dbl&gt; &lt;date&gt;     &lt;chr&gt; &lt;chr&gt;          &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1      704   2002 2002-03-11 GB    NE              2002       4     126       0
 2      704   2002 2002-03-11 NE    GB                NA      NA      NA      NA
 3      716   2002 2002-04-20 NE    WAS             2002       1      32       0
 4      716   2002 2002-04-20 NE    WAS             2002       3      96       0
 5      716   2002 2002-04-20 NE    WAS             2002       7     234       0
 6      716   2002 2002-04-20 WAS   NE              2002       1      21       0
 7      725   2002 2002-04-21 DEN   NE              2002       4     117       0
 8      725   2002 2002-04-21 NE    DEN             2002       4     131       0
 9      725   2002 2002-04-21 NE    DEN             2002       5     144       0
10      727   2002 2002-04-21 DAL   NE              2002       7     237       0
# ... with 488 more rows, 2 more variables: pfr_id &lt;chr&gt;, pfr_name &lt;chr&gt;, and
#   abbreviated variable names 1: pick_round, 2: pick_number, 3: conditional</code></pre>
</div>
</div>
<p>If you want to view a trade that involves a specific player, you can do the same as above but <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> for a specific player. As an example, we do search for the trade that resulted in the New England Patriots sending Drew Bledsoe to the Buffalo Bills.</p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">bledsoe_trade</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_trades.html">load_trades</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">trade_id</span> <span class="op">==</span> <span class="va">trade_id</span><span class="op">[</span><span class="va">pfr_name</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Drew Bledsoe"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></span>
<span></span>
<span><span class="va">bledsoe_trade</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 x 11
  trade~1 season trade_date gave  recei~2 pick_~3 pick_~4 pick_~5 condi~6 pfr_id
    &lt;dbl&gt;  &lt;dbl&gt; &lt;date&gt;     &lt;chr&gt; &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt; 
1     728   2002 2002-04-22 BUF   NE         2003       1      14       0 HaynM~
2     728   2002 2002-04-22 NE    BUF          NA      NA      NA      NA BledD~
# ... with 1 more variable: pfr_name &lt;chr&gt;, and abbreviated variable names
#   1: trade_id, 2: received, 3: pick_season, 4: pick_round, 5: pick_number,
#   6: conditional</code></pre>
</div>
</div>
<p>Since the <code>load_trades()</code> function also includes NFL Draft round and pick numbers (if included in a trade), we can also - for example - determine all trades that involved a top ten pick switching hands.</p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">top_ten_picks</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_trades.html">load_trades</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">pick_round</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">&amp;</span> <span class="va">pick_number</span> <span class="op">&lt;=</span> <span class="fl">10</span><span class="op">)</span></span>
<span></span>
<span><span class="va">top_ten_picks</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 51 x 11
   trade_id season trade_date gave  received pick_season pick_~1 pick_~2 condi~3
      &lt;dbl&gt;  &lt;dbl&gt; &lt;date&gt;     &lt;chr&gt; &lt;chr&gt;          &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
 1      711   2002 2002-04-20 DAL   KC              2002       1       6       0
 2      711   2002 2002-04-20 KC    DAL             2002       1       8       0
 3      661   2003 2003-04-26 CHI   NYJ             2003       1       4       0
 4      662   2003 2003-04-26 ARI   NO              2003       1       6       0
 5       16   2004 2004-04-24 CLE   DET             2004       1       7       0
 6       16   2004 2004-04-24 DET   CLE             2004       1       6       0
 7       64   2005 2005-03-03 OAK   MIN             2005       1       7       0
 8      189   2007 2007-03-22 ATL   HOU             2007       1      10       0
 9      189   2007 2007-03-22 HOU   ATL             2007       1       8       0
10      197   2007 2007-04-28 SF    NE              2008       1       7       0
# ... with 41 more rows, 2 more variables: pfr_id &lt;chr&gt;, pfr_name &lt;chr&gt;, and
#   abbreviated variable names 1: pick_round, 2: pick_number, 3: conditional</code></pre>
</div>
</div>
</section><section id="the-load_draft_picks-function" class="level3" data-number="4.4.7"><h3 data-number="4.4.7" class="anchored" data-anchor-id="the-load_draft_picks-function">
<span class="header-section-number">4.4.7</span> The <code>load_draft_picks()</code> Function</h3>
<p>The <code>load_draft_picks()</code> function will load information pertaining to every draft pick dating back to 1980. Aside from the information you would expect (the player’s name, the team that draft, round, pick number, position, etc.), the <code>load_draft_picks()</code> function also includes data regarding how many seasons the player played, the amount of times they were named to Pro Bowls, and top-level statistics regarding rushing, passing, receiving, and defensive metrics.</p>
<p>The <code>load_draft_picks()</code> function can be used to explore multiple different facets of the NFL Draft. For example, there is a belief in the analytics community to never draft a running back in the first round. Without getting into the reasoning behind that belief, we can quickly create a visualization of career rushing yards per running back compared to their draft position.</p>
<div class="cell">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">draft_picks</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_draft_picks.html">load_draft_picks</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="va">teams</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_teams.html">load_teams</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="va">rb_picks</span> <span class="op">&lt;-</span> <span class="va">draft_picks</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">position</span> <span class="op">==</span> <span class="st">"RB"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">pick</span>, <span class="va">team</span>, <span class="va">rush_atts</span>, <span class="va">rush_yards</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">pick</span> <span class="op">&lt;=</span> <span class="fl">100</span><span class="op">)</span></span>
<span></span>
<span><span class="va">rb_picks</span> <span class="op">&lt;-</span> <span class="va">rb_picks</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span><span class="va">teams</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"team"</span> <span class="op">=</span> <span class="st">"team_abbr"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-fig.dpi="400">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">rb_picks</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">rush_yards</span>, y <span class="op">=</span> <span class="va">pick</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>color <span class="op">=</span> <span class="va">rb_picks</span><span class="op">$</span><span class="va">team_color</span>, size <span class="op">=</span> <span class="va">rb_picks</span><span class="op">$</span><span class="va">rush_atts</span> <span class="op">/</span> <span class="fl">500</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/pretty_breaks.html">pretty_breaks</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/pretty_breaks.html">pretty_breaks</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>                     labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/comma.html">comma_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Career Rushing Yards"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Pick Number"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">nfl_analytics_theme</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"**Career Rushing Yards vs. Pick Number**"</span>,</span>
<span>       subtitle <span class="op">=</span> <span class="st">"1980 to 2022"</span>,</span>
<span>       caption <span class="op">=</span> <span class="st">"*An Introduction to NFL Analytics with R*&lt;br&gt;**Brad J. Congelio**"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03-nfl-analytics-functions_files/figure-html/running-back-plot-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>According to the plot, there has been a limited number of running backs draft in the top 20 to go over 10,000 career yards. However, there are more running backs - some still active - drafted in the mid-range of the draft that are approaching, or have eclipsed, the 10,000 yard mark.</p>
</section><section id="the-load_combine-function" class="level3" data-number="4.4.8"><h3 data-number="4.4.8" class="anchored" data-anchor-id="the-load_combine-function">
<span class="header-section-number">4.4.8</span> The <code>load_combine()</code> Function</h3>
<p>The <code>load_combine()</code> function provides NFL Combine data dating back to 2000. Aside from biographical information for each player (including eventual draft position), the data include the player’s scores in the 40-yard dash, the bench press, the vertical, the broad jump, the cone drill, and the shuttle drill.</p>
<p>We can join information from <code>load_combine()</code> with outside information to determine if there is any correlation between a running back’s 40-yard dash time in the combine and the total number of rushing yard accumulated during his career.</p>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">combine_data</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_combine.html">load_combine</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">pfr_id</span>, <span class="va">forty</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">pfr_id</span><span class="op">)</span> <span class="op">&amp;</span> <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">forty</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">rosters</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_rosters.html">load_rosters</a></span><span class="op">(</span><span class="fl">2000</span><span class="op">:</span><span class="fl">2022</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">gsis_id</span>, <span class="va">pfr_id</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">distinct</span><span class="op">(</span><span class="va">gsis_id</span>, .keep_all <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="va">player_stats</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_player_stats.html">load_player_stats</a></span><span class="op">(</span>seasons <span class="op">=</span> <span class="cn">TRUE</span>, stat_type <span class="op">=</span> <span class="st">"offense"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">position</span> <span class="op">==</span> <span class="st">"RB"</span> <span class="op">&amp;</span> <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">player_name</span><span class="op">)</span> <span class="op">&amp;</span> <span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_name</span>, <span class="va">player_id</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">summarize</span><span class="op">(</span>total_yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">rushing_yards</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            team <span class="op">=</span> <span class="fu">last</span><span class="op">(</span><span class="va">recent_team</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">player_stats</span> <span class="op">&lt;-</span> <span class="va">player_stats</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span><span class="va">rosters</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"player_id"</span> <span class="op">=</span> <span class="st">"gsis_id"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">player_stats</span> <span class="op">&lt;-</span> <span class="va">player_stats</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">pfr_id</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">player_stats</span> <span class="op">&lt;-</span> <span class="va">player_stats</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span><span class="va">combine_data</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"pfr_id"</span> <span class="op">=</span> <span class="st">"pfr_id"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">forty</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">player_stats</span> <span class="op">&lt;-</span> <span class="va">player_stats</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span><span class="va">teams</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"team"</span> <span class="op">=</span> <span class="st">"team_abbr"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-fig.dpi="400">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">player_stats</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">forty</span>, y <span class="op">=</span> <span class="va">total_yards</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>color <span class="op">=</span> <span class="va">player_stats</span><span class="op">$</span><span class="va">team_color</span>, size <span class="op">=</span> <span class="fl">3.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="va">lm</span>, se <span class="op">=</span> <span class="cn">FALSE</span>, color <span class="op">=</span> <span class="st">"black"</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span>, size <span class="op">=</span> <span class="fl">0.8</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/pretty_breaks.html">pretty_breaks</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/pretty_breaks.html">pretty_breaks</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>                     labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/comma.html">comma_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">nfl_analytics_theme</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Forty-Yard Dash Time"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Career Rushing Yards"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"**Forty-Yard Dash Time vs. Career Rushing Yards**"</span>,</span>
<span>       subtitle <span class="op">=</span> <span class="st">"2000 to 2022"</span>,</span>
<span>       caption <span class="op">=</span> <span class="st">"*An Introduction to NFL Analytics with R*&lt;br&gt;**Brad J. Congelio**"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03-nfl-analytics-functions_files/figure-html/running-back-40-plot-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>The visualization indicates that there is little, if any, direct correlation between a running back’s 40-yard dash time and his career total rushing yards. There are likely other factors that contribute to total rushing yards, such as a running back’s agility and vision and - perhaps most important - the quality of the offensive line over the duration of the running back’s career.</p>
</section><section id="the-load_nextgen_stats-function" class="level3" data-number="4.4.9"><h3 data-number="4.4.9" class="anchored" data-anchor-id="the-load_nextgen_stats-function">
<span class="header-section-number">4.4.9</span> The <code>load_nextgen_stats()</code> Function</h3>
<p>The <code>load_nextgen_stats()</code> function retrieves player-level weekly statistics as provided by NFL Next Gen Stats dating back to the 2016 season. While three different stat types are provided (passing, receiving, and rushing), it is important to note that the data will only contain those players above a minimum number of attempts as determined by the NFL Next Gen Stats team.</p>
<p>To illustrate what can be done with the <code>load_nextgen_stats()</code> function, we will gather information to create two different plots. First, we can plot each quarterback’s average time to throw against their average completed air yards. Second, we will construct a graph to highlight which running backs had more actual rushing yards than the NGS “expected rushing yards” model.</p>
<div class="cell">
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ngs_data_passing</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_nextgen_stats.html">load_nextgen_stats</a></span><span class="op">(</span>seasons <span class="op">=</span> <span class="fl">2022</span>, stat_type <span class="op">=</span> <span class="st">"passing"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">week</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">player_display_name</span>, <span class="va">team_abbr</span>, <span class="va">avg_time_to_throw</span>, <span class="va">avg_completed_air_yards</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ngs_data_passing</span> <span class="op">&lt;-</span> <span class="va">ngs_data_passing</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span><span class="va">teams</span>, b <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"team_abbr"</span> <span class="op">=</span> <span class="st">"team_abbr"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-fig.dpi="400">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">ngs_data_passing</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">avg_time_to_throw</span>, y <span class="op">=</span> <span class="va">avg_completed_air_yards</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ngs_data_passing</span><span class="op">$</span><span class="va">avg_completed_air_yards</span><span class="op">)</span>,</span>
<span>             color <span class="op">=</span> <span class="st">"black"</span>, size <span class="op">=</span> <span class="fl">0.8</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_vline</span><span class="op">(</span>xintercept <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">ngs_data_passing</span><span class="op">$</span><span class="va">avg_time_to_throw</span><span class="op">)</span>,</span>
<span>             color <span class="op">=</span> <span class="st">"black"</span>, size <span class="op">=</span> <span class="fl">0.8</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3.5</span>, color <span class="op">=</span> <span class="va">ngs_data_passing</span><span class="op">$</span><span class="va">team_color</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/pretty_breaks.html">pretty_breaks</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>                     labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/comma.html">comma_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/pretty_breaks.html">pretty_breaks</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>                     labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/comma.html">comma_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_text_repel</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>label <span class="op">=</span> <span class="va">player_display_name</span><span class="op">)</span>,</span>
<span>                  family <span class="op">=</span> <span class="st">"Roboto Condensed"</span>, fontface <span class="op">=</span> <span class="st">"bold"</span>, size <span class="op">=</span> <span class="fl">3.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">nfl_analytics_theme</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Average Time to Throw"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Average Completed Air Yards"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"**Avgerage Time to Throw vs. Average Air Yards**"</span>,</span>
<span>       subtitle <span class="op">=</span> <span class="st">"2022 Regular Season"</span>,</span>
<span>       caption <span class="op">=</span> <span class="st">"*An Introduction to NFL Analytics with R*&lt;br&gt;**Brad J. Congelio**"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03-nfl-analytics-functions_files/figure-html/ngs-passing-plot-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>The resulting plot shows that Dak Prescott, Jalen Hurts, and Ryan Tannehill had an average completed air yard above the NFL average despite getting rid of the ball quicker than most other quarterbacks in the league. Conversely, Patrick Mahomes, Daniel Jones, and Justin Herbert has under average completed air yards despite holding on to the ball longer than the rest of the league (on average).</p>
<div class="cell">
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ngs_data_rushing</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_nextgen_stats.html">load_nextgen_stats</a></span><span class="op">(</span>seasons <span class="op">=</span> <span class="fl">2022</span>, stat_type <span class="op">=</span> <span class="st">"rushing"</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">week</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">player_display_name</span>, <span class="va">team_abbr</span>, <span class="va">expected_rush_yards</span>, <span class="va">rush_yards_over_expected</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">mutate</span><span class="op">(</span>actual_rush_yards <span class="op">=</span> <span class="va">expected_rush_yards</span> <span class="op">+</span> <span class="va">rush_yards_over_expected</span><span class="op">)</span></span>
<span></span>
<span><span class="va">ngs_data_rushing</span> <span class="op">&lt;-</span> <span class="va">ngs_data_rushing</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">left_join</span><span class="op">(</span><span class="va">teams</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"team_abbr"</span> <span class="op">=</span> <span class="st">"team_abbr"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-fig.dpi="400">
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">ngs_data_rushing</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">expected_rush_yards</span>, y <span class="op">=</span> <span class="va">actual_rush_yards</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="va">lm</span>, se <span class="op">=</span> <span class="cn">FALSE</span>, color <span class="op">=</span> <span class="st">"black"</span>, size <span class="op">=</span> <span class="fl">0.8</span>, linetype <span class="op">=</span> <span class="st">"dashed"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3.5</span>, color <span class="op">=</span> <span class="va">ngs_data_rushing</span><span class="op">$</span><span class="va">team_color</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_x_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/pretty_breaks.html">pretty_breaks</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>                     labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/comma.html">comma_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">scale_y_continuous</span><span class="op">(</span>breaks <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/pretty_breaks.html">pretty_breaks</a></span><span class="op">(</span><span class="op">)</span>,</span>
<span>                     labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/comma.html">comma_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_text_repel</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>label <span class="op">=</span> <span class="va">player_display_name</span><span class="op">)</span>, family <span class="op">=</span> <span class="st">"Roboto Condensed"</span>, fontface <span class="op">=</span> <span class="st">"bold"</span>, size <span class="op">=</span> <span class="fl">3.5</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">nfl_analytics_theme</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">xlab</span><span class="op">(</span><span class="st">"Expected Rush Yards"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">ylab</span><span class="op">(</span><span class="st">"Actual Rush Yards"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Expected Rush Yards vs. Actual Rush Yards"</span>,</span>
<span>       subtitle <span class="op">=</span> <span class="st">"2022 Regular Season"</span>,</span>
<span>       caption <span class="op">=</span> <span class="st">"*An Introduction to NFL Analytics with R*&lt;br&gt;**Brad J. Congelio**"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="03-nfl-analytics-functions_files/figure-html/ngs-rushing-plot-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>After plotting the rushing data from Next Gen Stats, we can see that Nick Chubb was well above the expected yardage metric while Ezekiel Elliott, Alvin Kamara, Najee Harris, and Dalvin Cook all had actual rushing yards that fell below what was expected by the model.</p>
</section><section id="the-load_depth_charts-function" class="level3" data-number="4.4.10"><h3 data-number="4.4.10" class="anchored" data-anchor-id="the-load_depth_charts-function">
<span class="header-section-number">4.4.10</span> The <code>load_depth_charts()</code> Function</h3>
<p>fffffff</p>
</section><section id="the-load_injuries-function" class="level3" data-number="4.4.11"><h3 data-number="4.4.11" class="anchored" data-anchor-id="the-load_injuries-function">
<span class="header-section-number">4.4.11</span> The <code>load_injuries()</code> Function</h3>
<p>fffffff</p>
</section><section id="the-load_espn_qbr-function" class="level3" data-number="4.4.12"><h3 data-number="4.4.12" class="anchored" data-anchor-id="the-load_espn_qbr-function">
<span class="header-section-number">4.4.12</span> The <code>load_espn_qbr()</code> Function</h3>
<p>ffffff</p>
</section><section id="the-load_pfr_advstats-function" class="level3" data-number="4.4.13"><h3 data-number="4.4.13" class="anchored" data-anchor-id="the-load_pfr_advstats-function">
<span class="header-section-number">4.4.13</span> The <code>load_pfr_advstats()</code> Function</h3>
<p>fffffff</p>
</section><section id="the-load_snap_counts-function" class="level3" data-number="4.4.14"><h3 data-number="4.4.14" class="anchored" data-anchor-id="the-load_snap_counts-function">
<span class="header-section-number">4.4.14</span> The <code>load_snap_counts()</code> Function</h3>
<p>fffffff</p>
</section><section id="the-load_contracts-function" class="level3" data-number="4.4.15"><h3 data-number="4.4.15" class="anchored" data-anchor-id="the-load_contracts-function">
<span class="header-section-number">4.4.15</span> The <code>load_contracts()</code> Function</h3>
<p>fffffff</p>
</section><section id="the-clean_player_names-function" class="level3" data-number="4.4.16"><h3 data-number="4.4.16" class="anchored" data-anchor-id="the-clean_player_names-function">
<span class="header-section-number">4.4.16</span> The <code>clean_player_names()</code> Function</h3>
<p>ffffff</p>
</section><section id="the-clean_team_abbrs-function" class="level3" data-number="4.4.17"><h3 data-number="4.4.17" class="anchored" data-anchor-id="the-clean_team_abbrs-function">
<span class="header-section-number">4.4.17</span> The <code>clean_team_abbrs()</code> Function</h3>
<p>ffffff</p>
</section><section id="the-clean_homeaway-function" class="level3" data-number="4.4.18"><h3 data-number="4.4.18" class="anchored" data-anchor-id="the-clean_homeaway-function">
<span class="header-section-number">4.4.18</span> The <code>clean_homeaway()</code> Function</h3>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./02-nfl-analytics-tidyverse.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Wrangling NFL Data in the <code>tidyverse</code></span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04-nfl-analytics-visualization.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data Visualization with NFL Analytics</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">NFL Analytics with R was written by Bradley J. Congelio.</div>   
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a></div>
  </div>
</footer>


<script src="https://platform.twitter.com/widgets.js"></script>
</body></html>