<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 1 An Introduction to NFL Analytics and the R Programming Language | An Introduction to NFL Analytics with R</title>
<meta name="author" content="Bradley J. Congelio">
<meta name="description" content="Need to discuss nflfastR versus nflreadr prior to all of this. Basically comes down to loading both packages but, ultimately, mostly using nflreadr since it has become a “catch all” package for...">
<meta name="generator" content="bookdown 0.26 with bs4_book()">
<meta property="og:title" content="Chapter 1 An Introduction to NFL Analytics and the R Programming Language | An Introduction to NFL Analytics with R">
<meta property="og:type" content="book">
<meta property="og:url" content="https://bradcongelio.com/nfl-analytics-with-r-book/an-introduction-to-nfl-analytics-and-the-r-programming-language.html">
<meta property="og:description" content="Need to discuss nflfastR versus nflreadr prior to all of this. Basically comes down to loading both packages but, ultimately, mostly using nflreadr since it has become a “catch all” package for...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 1 An Introduction to NFL Analytics and the R Programming Language | An Introduction to NFL Analytics with R">
<meta name="twitter:description" content="Need to discuss nflfastR versus nflreadr prior to all of this. Basically comes down to loading both packages but, ultimately, mostly using nflreadr since it has become a “catch all” package for...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1.9000/transition.js"></script><script src="libs/bs3compat-0.3.1.9000/tabs.js"></script><script src="libs/bs3compat-0.3.1.9000/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">An Introduction to NFL Analytics with R</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Preface</a></li>
<li><a class="active" href="an-introduction-to-nfl-analytics-and-the-r-programming-language.html"><span class="header-section-number">1</span> An Introduction to NFL Analytics and the R Programming Language</a></li>
<li><a class="" href="wrangling-nfl-data-in-the-tidyverse.html"><span class="header-section-number">2</span> Wrangling NFL Data in the tidyverse</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="an-introduction-to-nfl-analytics-and-the-r-programming-language" class="section level1" number="1">
<h1>
<span class="header-section-number">1</span> An Introduction to NFL Analytics and the R Programming Language<a class="anchor" aria-label="anchor" href="#an-introduction-to-nfl-analytics-and-the-r-programming-language"><i class="fas fa-link"></i></a>
</h1>
<p>Need to discuss <code>nflfastR</code> versus <code>nflreadr</code> prior to all of this. Basically comes down to loading both packages but, ultimately, mostly using <code>nflreadr</code> since it has become a “catch all” package for the <code>nflverse</code>.</p>
<p>As well, if you do not yet have R, RStudio, and the required packages loaded, please see Chapter ## for instructions on getting all of the necessary components installed on your computer.</p>
<div id="nflreadr-weekly-vs.-play-by-play-stats" class="section level2" number="1.1">
<h2>
<span class="header-section-number">1.1</span> <code>nflreadr</code>: Weekly vs. Play-by-Play Stats<a class="anchor" aria-label="anchor" href="#nflreadr-weekly-vs.-play-by-play-stats"><i class="fas fa-link"></i></a>
</h2>
<p>Within <code>nflreadr</code>, you have two main options for retrieving NFL statistics. The first is running the function <code>load_player_stats()</code> while the other is <code>load_pbp</code>.</p>
<p>There is a <strong>very important distinction between the two</strong>.</p>
<p>Take this example: let’s say you want to get Ben Roethlisberger’s total passing yards from the 2021 season and start to do so using the <code>load_pbp</code> function:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_pbp.html">load_pbp</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span>

<span class="va">ben.passing</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">passer</span> <span class="op">==</span> <span class="st">"B.Roethlisberger"</span> <span class="op">&amp;</span> <span class="va">pass</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">&amp;</span> <span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>total.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">yards_gained</span>, na.rm <span class="op">=</span> <span class="cn">T</span><span class="op">)</span><span class="op">)</span>

<span class="fu">tibble</span><span class="op">(</span><span class="va">ben.passing</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   passer           total.yards
##   &lt;chr&gt;                  &lt;dbl&gt;
## 1 B.Roethlisberger        3523</code></pre>
<p>Based on the above code, using <code>load_pbp()</code>, we get a return that Ben Roethlisberger had 3,523 passing yards during the 2021 NFL regular season. However, if you check his <a href="https://www.pro-football-reference.com/players/R/RoetBe00.htm">Pro Football Reference page</a>, you will see that his actual number of passing yards during this period was 3,740.</p>
<p>So, what gives? Shouldn’t calcuating the total number of passing yards using the official NFL play-by-play data provide accurate results?</p>
<p>The short answer: it can, but it takes a bit more leg work to make it happen. To try to get it as close as possible using <code>load_pbp()</code>, we will have to add some other varibles into the <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> function:</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ben.updated</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">passer</span> <span class="op">==</span> <span class="st">"B.Roethlisberger"</span> <span class="op">&amp;</span> <span class="va">complete_pass</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">&amp;</span> <span class="va">sack</span> <span class="op">==</span> <span class="fl">0</span> <span class="op">&amp;</span> <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">down</span><span class="op">)</span> <span class="op">&amp;</span>
           <span class="va">penalty</span> <span class="op">==</span> <span class="fl">0</span> <span class="op">&amp;</span> <span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>total.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_yards</span>, na.rm <span class="op">=</span> <span class="cn">T</span><span class="op">)</span><span class="op">)</span>

<span class="fu">tibble</span><span class="op">(</span><span class="va">ben.updated</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   passer           total.yards
##   &lt;chr&gt;                  &lt;dbl&gt;
## 1 B.Roethlisberger        3674</code></pre>
<p>As you can see, numerous variables were added to the <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> function. To eliminate yardage loss due to sacks, we are now filtering to plays where <code>sack == 0</code>, meaning there is NOT a sack on the play. As well, we are filtering any plays where a <code>down</code> is not associated which drops any two-point conversion attempt. Finally, we are getting the yardage for just <code>complete_pass</code> and dropping any play where a penalty happened.</p>
<p>Unfortunately, despite this, we are closer but still short of Roethlisberger’s total passing yards during the 2021 regular season as the code above results in an output of 3,674 yards, meaning we are still looking for a missing 66 yards somewhere in the data.</p>
<p>This is a perfect example of the difference between <code>load_pbp()</code> and <code>load_player_stats()</code>. In the case of the first, it can be exceedingly difficult to get the “official statistics” to output because of the number of variables that need to be accounted for.</p>
<p>Fortunately, the <code>nflverse</code> team developed the <code>load_player_stats()</code> function to avoid this type of problem. As an example, let’s do the same scenario as above:</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">weekly.data</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_player_stats.html">load_player_stats</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span>

<span class="va">ben.weekly</span> <span class="op">&lt;-</span> <span class="va">weekly.data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_name</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">player_name</span> <span class="op">==</span> <span class="st">"B.Roethlisberger"</span> <span class="op">&amp;</span> <span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>total.yards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_yards</span><span class="op">)</span><span class="op">)</span>

<span class="fu">tibble</span><span class="op">(</span><span class="va">ben.weekly</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   player_name      total.yards
##   &lt;chr&gt;                  &lt;dbl&gt;
## 1 B.Roethlisberger        3740</code></pre>
<p>Without needing to add multiple variables into the <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> function, we have hit Roethlisberger’s total passing yards during the 2021 regular season right on with 3,740 yards.</p>
<p>This highlights the important distinction between <code>load_pbp()</code> and <code>load_player_stats()</code>: you should plan to use <code>load_pbp()</code> if you need the full context (meaning, looking at statistics based on down, distance, time, etc.) while <code>load_player_stats()</code> should be used when you are looking for a player’s numbers regardless of other outside variables.</p>
<p>That said, there could be situations where you need to use both functions. Later in this chapter we will cover how to correctly merge data collected from both the <code>load_pbp()</code> and <code>load_player_stats()</code> functions.</p>
</div>
<div id="using-load_pbp-to-add-context-to-statistics" class="section level2" number="1.2">
<h2>
<span class="header-section-number">1.2</span> Using <code>load_pbp()</code> to Add Context to Statistics<a class="anchor" aria-label="anchor" href="#using-load_pbp-to-add-context-to-statistics"><i class="fas fa-link"></i></a>
</h2>
<p>As just mentioned above, using the <code>load_pbp()</code> function is preferable when you are looking to add context to a player’s statistics, as the <code>load_player_stats()</code> function is, for all intents and purposes, aggregated statistics devoid of any deeper meaning.</p>
<p>To highlight this, let’s look at an example of how context can be added to a player’s statistics using <code>load_pbp()</code>.</p>
<div id="an-example-qb-aggresiveness-on-3rd-down" class="section level3" number="1.2.1">
<h3>
<span class="header-section-number">1.2.1</span> An Example: QB Aggresiveness on 3rd Down<a class="anchor" aria-label="anchor" href="#an-example-qb-aggresiveness-on-3rd-down"><i class="fas fa-link"></i></a>
</h3>
<p>Prior to the writing of this book, I created a metric using <code>load_pbp()</code> data I coined <strong>QB 3rd Down Aggressiveness</strong>. The metric is designed to determine <em>which QBs in the NFL are most aggressive in 3rd down situations by gauging how often they throw the ball to, or pass, the first down line.</em></p>
<p>First, let’s highlight the code used to create the results for this metric and then break it down line-by-line.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">aggressiveness</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer</span>, <span class="va">passer_id</span>, <span class="va">posteam</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">down</span> <span class="op">==</span> <span class="fl">3</span>, <span class="va">play_type</span> <span class="op">==</span> <span class="st">"pass"</span>, <span class="va">ydstogo</span> <span class="op">&gt;=</span> <span class="fl">5</span>, <span class="va">ydstogo</span> <span class="op">&lt;=</span> <span class="fl">10</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>total <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,
            aggressive <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">air_yards</span> <span class="op">&gt;=</span> <span class="va">ydstogo</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            percentage <span class="op">=</span> <span class="va">aggressive</span> <span class="op">/</span> <span class="va">total</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">total</span> <span class="op">&gt;=</span> <span class="fl">50</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">arrange</span><span class="op">(</span><span class="fu">desc</span><span class="op">(</span><span class="va">percentage</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'passer', 'passer_id'. You can override
## using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">tibble</span><span class="op">(</span><span class="va">aggressiveness</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 30 x 6
##    passer       passer_id  posteam total aggressive percentage
##    &lt;chr&gt;        &lt;chr&gt;      &lt;chr&gt;   &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;
##  1 D.Prescott   00-0033077 DAL        84         53      0.631
##  2 K.Murray     00-0035228 ARI        60         37      0.617
##  3 J.Hurts      00-0036389 PHI        65         40      0.615
##  4 P.Mahomes    00-0033873 KC         93         56      0.602
##  5 B.Mayfield   00-0034855 CLE        59         35      0.593
##  6 T.Lawrence   00-0036971 JAX        78         46      0.590
##  7 J.Herbert    00-0036355 LAC        87         51      0.586
##  8 D.Jones      00-0035710 NYG        60         35      0.583
##  9 T.Tagovailoa 00-0036212 MIA        60         35      0.583
## 10 M.Stafford   00-0026498 LA         95         54      0.568
## # ... with 20 more rows</code></pre>
<p>As you can see in the <code>tibble()</code> output of the results, Dak Prescott was the most aggressive quarterback in 3rd down passing situations in the 2021 season, passing to, our beyond, the line of gain just over 63% of the time.</p>
<p>After creating a new dataframe called <code>aggressiveness</code> from the 2021 play-by-play we originally collected using <code>data &lt;- nflreadr::load_pbp(2021)</code>, we use <code>group_by</code> to ensure that the data is being collected <em>per individual quarterback</em> and then appending both their unique <code>passer_id</code> as well as the <code>posteam</code> which is simply their team’s abbreviation (note: the <code>posteam</code> variable is not a vital part of the data collection/manipulation process, but does play an important role when taking this output into the data visualization process, which is covered in Chapter 4.</p>
<p>However, there are a couple items to point out and clarify with the above code. Moreover, there are certainly arguments to be made regarding how to “capture” scenarios in the data that require “aggressiveness.”</p>
<p>After using the <code>group_by</code> function to lump data with each individual QB, we then use <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> function. Of course, we only want those <code>play_types</code> that are “pass” on 3rd downs. However, in the above code, we are filtering for <em>just</em> those 3rd down situations where the <code>yards to go</code> are between five and ten yards.</p>
<p>Doing so was a personal decision on my end when creating the metric. My logic? If there were less than five yards to go on 3rd down, the opposing defense would not be able to “sell out” to the pass as it would not be out of the question for an offense to attempt to gain the first down on the ground. Conversely, anything <em>over</em> ten yards likely results in the defense selling out to the pass, thus leaving an imprint on the aggressiveness output of the quarterbacks.</p>
<p>For the sake of curiosity, we can edit the above code to include all passing attempts on 3rd down with under 10 yards to go for the first down:</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">aggressiveness.under.10</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer</span>, <span class="va">passer_id</span>, <span class="va">posteam</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">down</span> <span class="op">==</span> <span class="fl">3</span>, <span class="va">play_type</span> <span class="op">==</span> <span class="st">"pass"</span>, <span class="va">ydstogo</span> <span class="op">&lt;=</span> <span class="fl">10</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>total <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,
            aggressive <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">air_yards</span> <span class="op">&gt;=</span> <span class="va">ydstogo</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            percentage <span class="op">=</span> <span class="va">aggressive</span> <span class="op">/</span> <span class="va">total</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">total</span> <span class="op">&gt;=</span> <span class="fl">50</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">arrange</span><span class="op">(</span><span class="fu">desc</span><span class="op">(</span><span class="va">percentage</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'passer', 'passer_id'. You can override
## using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">tibble</span><span class="op">(</span><span class="va">aggressiveness.under.10</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 33 x 6
##    passer       passer_id  posteam total aggressive percentage
##    &lt;chr&gt;        &lt;chr&gt;      &lt;chr&gt;   &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;
##  1 K.Murray     00-0035228 ARI        98         67      0.684
##  2 J.Hurts      00-0036389 PHI       107         73      0.682
##  3 T.Lawrence   00-0036971 JAX       131         88      0.672
##  4 D.Prescott   00-0033077 DAL       136         89      0.654
##  5 J.Allen      00-0034857 BUF       138         88      0.638
##  6 J.Herbert    00-0036355 LAC       148         94      0.635
##  7 T.Tagovailoa 00-0036212 MIA        93         59      0.634
##  8 M.Stafford   00-0026498 LA        172        109      0.634
##  9 A.Rodgers    00-0023459 GB        128         80      0.625
## 10 D.Jones      00-0035710 NYG        85         53      0.624
## # ... with 23 more rows</code></pre>
<p>The results are quite different from the first running of this metric, as Dak Prescott is now the 4th most aggressive QB, while Kyler Murray moves to the top by approaching a nearly 70% aggressiveness rate on 3rd down. This small change highlights an important element about analytics: much of the work is the result of the coder (ie., <u>you</u>) being able to justify your decision-making process when developing the filters for each metric you create.</p>
<p>In this case, I stand by my argument that including just those pass attempts on 3rd down with between 5 and 10 yards to go is a more accurate assessment of aggressiveness as, for example, 3rd down with 8 yards to go is an obvious passing situation in <u>most</u> cases.</p>
<p>That begs the question, though: in which cases is 3rd down with 8 yards to go <u>not</u> an obvious passing situation?</p>
<div id="qb-aggressiveness-filtering-for-garbage-time" class="section level4" number="1.2.1.1">
<h4>
<span class="header-section-number">1.2.1.1</span> QB Aggressiveness: Filtering for “Garbage Time?”<a class="anchor" aria-label="anchor" href="#qb-aggressiveness-filtering-for-garbage-time"><i class="fas fa-link"></i></a>
</h4>
<p>In our initial running of the QB Aggressiveness metric, Josh Allen is the 15th most aggressive QB in the NFL on 3rd down with between 5 and 10 yards to go. But how much does the success of the Buffalo Bills play into that 15th place ranking?</p>
<p>The Bills, at the conclusion of the 2021 season, had the largest positive point differential in the league at 194 (the Bills scored 483 points, while allowing just 289). Perhaps Allen’s numbers are skewed because the Bills were so often playing with the lead late into the game?</p>
<p>To account for this, we can add information into the <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code> function to attempt to remove what are referenced to in the analytics community as “garbage time stats.”</p>
<p>Let’s add the “garbage time” filter to the code we’ve already prepared:</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">aggressiveness.garbage</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">passer</span>, <span class="va">passer_id</span>, <span class="va">posteam</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">down</span> <span class="op">==</span> <span class="fl">3</span>, <span class="va">play_type</span> <span class="op">==</span> <span class="st">"pass"</span>, <span class="va">ydstogo</span> <span class="op">&gt;=</span> <span class="fl">5</span>, <span class="va">ydstogo</span> <span class="op">&lt;=</span> <span class="fl">10</span>,
         <span class="va">wp</span> <span class="op">&gt;</span> <span class="fl">.05</span>, <span class="va">wp</span> <span class="op">&lt;</span> <span class="fl">.95</span>, <span class="va">half_seconds_remaining</span> <span class="op">&gt;</span> <span class="fl">120</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>total <span class="op">=</span> <span class="fu">n</span><span class="op">(</span><span class="op">)</span>,
            aggressive <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">air_yards</span> <span class="op">&gt;=</span> <span class="va">ydstogo</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,
            percentage <span class="op">=</span> <span class="va">aggressive</span> <span class="op">/</span> <span class="va">total</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">total</span> <span class="op">&gt;=</span> <span class="fl">50</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">arrange</span><span class="op">(</span><span class="fu">desc</span><span class="op">(</span><span class="va">percentage</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'passer', 'passer_id'. You can override
## using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">tibble</span><span class="op">(</span><span class="va">aggressiveness.garbage</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 26 x 6
##    passer     passer_id  posteam total aggressive percentage
##    &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;   &lt;int&gt;      &lt;int&gt;      &lt;dbl&gt;
##  1 D.Prescott 00-0033077 DAL        61         40      0.656
##  2 T.Lawrence 00-0036971 JAX        51         33      0.647
##  3 K.Murray   00-0035228 ARI        51         31      0.608
##  4 M.Stafford 00-0026498 LA         79         48      0.608
##  5 P.Mahomes  00-0033873 KC         68         41      0.603
##  6 D.Jones    00-0035710 NYG        50         30      0.6  
##  7 J.Herbert  00-0036355 LAC        67         38      0.567
##  8 M.Jones    00-0036972 NE         57         31      0.544
##  9 J.Allen    00-0034857 BUF        59         32      0.542
## 10 R.Wilson   00-0029263 SEA        56         30      0.536
## # ... with 16 more rows</code></pre>
<p>We are now using the same code, but have included three new items to the <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code>. First, we are stipulating that, aside from the down and distance inclusion, we only want those plays that occured when the offense’s <code>win probability</code> was between 5% and 95%, as well as ensuring that the plays did not happen after the two-minute warning of either half.</p>
<p>The decision on range of the <code>win probability</code> numbers is, again, a personal preference. When <code>nflfastR</code> was first released, analyst often used a 20-80% range for <code>win probability</code>. However, Sebastian Carl - one of the creators of the <code>nflverse</code> explained in the package’s Discord:</p>
<blockquote>
<p>Sebastian Carl: “I am generally very conservative with filtering plays using wp. Especially the vegas wp model can reach &gt;85% probs early in the game because it incorporates market lines. I never understood the 20% &lt;= wp &lt;= 80%”garbage time" filter. This is removing a ton of plays. My general advice is a lower boundary of something around 5% (i.e., 5% &lt;= wp &lt;= 95%).</p>
</blockquote>
<p>Ben Baldwin followed up on Carl’s thoughts:</p>
<blockquote>
<p>Ben Baldwin: “agree with this. 20-80% should only be used as a filter for looking at how run-heavy a team is (because outside of this range is when teams change behavior a lot). and possibly how teams behave on 4th downs. but not for team or player performance.”</p>
</blockquote>
<p>Based on that advice, I typically stick to the 5-95% range when filtering for <code>win probability</code> using play-by-play data. And, in this case, it did have an impact.</p>
<p>As mentioned, prior to filtering for garbage time, Allen was the 15th most aggressive QB in the league at nearly 52%. However, once filtering for garbage time, Allen rose to 9th most aggressive QB, with a slight increase of percentage to 54%.</p>
<p>What is interesting about the above example, though, is Dak Prescott and the Cowboys. Dallas maintained the second largest point differntial in the league (530 points for and 358 points against, for a 172 point difference). Without the garbage time filter, Prescott was tops in the NFL with an aggressiveness rating of 63%.</p>
<p>Once adjusted for garbage time? Prescott remained atop the NFL with an aggressiveness rating of 65.5%.</p>
<p>Allen’s increase in the standings, and Prescott remaining best in the league, in this specific metric, is a possible indicator that the inclusion of the “garbage time” filters provides a slightly more accurate result.</p>
</div>
</div>
<div id="the-inclusion-of-contextual-statistics" class="section level3" number="1.2.2">
<h3>
<span class="header-section-number">1.2.2</span> The Inclusion of Contextual Statistics<a class="anchor" aria-label="anchor" href="#the-inclusion-of-contextual-statistics"><i class="fas fa-link"></i></a>
</h3>
<p>As seen in the above example regarding QB aggressiveness on 3rd down, the using of the <code>load_pbp()</code> function provides the ability to create situation specific metrics that would otherwise be lost in aggregated weekly statistics.</p>
</div>
</div>
<div id="using-load_player_stats-to-find-leaders" class="section level2" number="1.3">
<h2>
<span class="header-section-number">1.3</span> Using <code>load_player_stats()</code> To Find Leaders<a class="anchor" aria-label="anchor" href="#using-load_player_stats-to-find-leaders"><i class="fas fa-link"></i></a>
</h2>
<p>While using <code>load_player_stats()</code> does not provide the ability to add context to your analysis, it does provide an easy and efficient way to determine weekly or season-long leaders over many top-level, widely-used NFL statistics. In the below example, we will determine the 2021 leaders in air yards per attempt.</p>
<div id="an-example-2021-qb-air-yards-per-attempt-leaders" class="section level3" number="1.3.1">
<h3>
<span class="header-section-number">1.3.1</span> An Example: 2021 QB Air Yards per Attempt Leaders<a class="anchor" aria-label="anchor" href="#an-example-2021-qb-air-yards-per-attempt-leaders"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu">nflreadr</span><span class="fu">::</span><span class="fu"><a href="https://nflreadr.nflverse.com/reference/load_player_stats.html">load_player_stats</a></span><span class="op">(</span><span class="fl">2021</span><span class="op">)</span>

<span class="va">ay.per.attempt</span> <span class="op">&lt;-</span> <span class="va">data</span> <span class="op">%&gt;%</span>
  <span class="fu">group_by</span><span class="op">(</span><span class="va">player_name</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">season_type</span> <span class="op">==</span> <span class="st">"REG"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">summarize</span><span class="op">(</span>n.attempts <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">attempts</span><span class="op">)</span>,
            n.airyards <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">passing_air_yards</span><span class="op">)</span>,
            ay.attempt <span class="op">=</span> <span class="va">n.airyards</span> <span class="op">/</span> <span class="va">n.attempts</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">n.attempts</span> <span class="op">&gt;=</span> <span class="fl">400</span><span class="op">)</span></code></pre></div>
</div>
</div>
<div id="retrieving-multiple-data-for-multiple-seasons" class="section level2" number="1.4">
<h2>
<span class="header-section-number">1.4</span> Retrieving Multiple Data for Multiple Seasons<a class="anchor" aria-label="anchor" href="#retrieving-multiple-data-for-multiple-seasons"><i class="fas fa-link"></i></a>
</h2>
</div>
<div id="other-sources-of-data-for-nfl-analytics" class="section level2" number="1.5">
<h2>
<span class="header-section-number">1.5</span> Other Sources of Data for NFL Analytics<a class="anchor" aria-label="anchor" href="#other-sources-of-data-for-nfl-analytics"><i class="fas fa-link"></i></a>
</h2>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="index.html">Preface</a></div>
<div class="next"><a href="wrangling-nfl-data-in-the-tidyverse.html"><span class="header-section-number">2</span> Wrangling NFL Data in the tidyverse</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#an-introduction-to-nfl-analytics-and-the-r-programming-language"><span class="header-section-number">1</span> An Introduction to NFL Analytics and the R Programming Language</a></li>
<li><a class="nav-link" href="#nflreadr-weekly-vs.-play-by-play-stats"><span class="header-section-number">1.1</span> nflreadr: Weekly vs. Play-by-Play Stats</a></li>
<li>
<a class="nav-link" href="#using-load_pbp-to-add-context-to-statistics"><span class="header-section-number">1.2</span> Using load_pbp() to Add Context to Statistics</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#an-example-qb-aggresiveness-on-3rd-down"><span class="header-section-number">1.2.1</span> An Example: QB Aggresiveness on 3rd Down</a></li>
<li><a class="nav-link" href="#the-inclusion-of-contextual-statistics"><span class="header-section-number">1.2.2</span> The Inclusion of Contextual Statistics</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#using-load_player_stats-to-find-leaders"><span class="header-section-number">1.3</span> Using load_player_stats() To Find Leaders</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#an-example-2021-qb-air-yards-per-attempt-leaders"><span class="header-section-number">1.3.1</span> An Example: 2021 QB Air Yards per Attempt Leaders</a></li></ul>
</li>
<li><a class="nav-link" href="#retrieving-multiple-data-for-multiple-seasons"><span class="header-section-number">1.4</span> Retrieving Multiple Data for Multiple Seasons</a></li>
<li><a class="nav-link" href="#other-sources-of-data-for-nfl-analytics"><span class="header-section-number">1.5</span> Other Sources of Data for NFL Analytics</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>An Introduction to NFL Analytics with R</strong>" was written by Bradley J. Congelio. It was last built on 2022-06-18.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>
</body>
</html>
